(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var u2=function(a){a.V("cardstatechange",g.jX(a)&&g.kX(a)?1:0)},yDa=function(a){var b=g.vg(a);
a=g.Bg(a);return new g.eg(b.x,b.y,a.width,a.height)},zDa=function(a){return Math.pow(a,3)},ADa=function(a){return 3*a*a-2*a*a*a},x2=function(a){a=g.Ua(a);
delete v2[a];g.Wb(v2)&&w2&&w2.stop()},CDa=function(){w2||(w2=new g.E(function(){BDa()},20));
var a=w2;a.isActive()||a.start()},BDa=function(){var a=g.A();
g.Ib(v2,function(b){DDa(b,a)});
g.Wb(v2)||CDa()},y2=function(a,b,c,d){g.Bn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.K=b;this.duration=c;this.F=d;this.coords=[];this.progress=this.G=0;this.D=null},DDa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.G=1E3/(b-a.D);a.D=b;EDa(a,a.progress);1==a.progress?(a.Ha=0,x2(a),a.Jf(),a.Op()):a.Jb()&&a.Aw()},EDa=function(a,b){"function"===typeof a.F&&(b=a.F(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.K[c]-a.u[c])*b+a.u[c]},FDa=function(a,b){g.Il.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.G;this.state=b.Ha},z2=function(a,b,c,d,e){y2.call(this,b,c,d,e);
this.element=a},A2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
z2.call(this,a,b,c,d,e)},B2=function(a){g.B.call(this);
this.B=a||window;this.u=[]},C2=function(a){return a.baseUrl||null},D2=function(a,b){return g.Je(g.Pc(a,b,void 0),function(c){return!!c})},GDa=function(a,b,c){function d(Xa){var Kb,eb,ce,ad=Xa.hovercardButton;
if(!ad)return null;ad=ad.subscribeButtonRenderer;if(!ad)return null;var Gi=f(ad.unsubscribedButtonText),Hi=f(ad.subscribedButtonText);if(ad.subscribed){var Jh=f(ad.subscriberCountWithUnsubscribeText);var Ii=f(ad.subscriberCountText)}else Jh=f(ad.subscriberCountText),Ii=f(ad.subscriberCountWithSubscribeText);var mf=null;return Xa.signinEndpoint&&(mf=g.Rb(Xa,"signinEndpoint","webNavigationEndpointData","url"),mf||(mf=null===(ce=null===(eb=null===(Kb=ad.signInEndpoint)||void 0===Kb?void 0:Kb.commandMetadata)||
void 0===eb?void 0:eb.webCommandMetadata)||void 0===ce?void 0:ce.url),!mf)?null:Gi&&(Hi||mf)?{subscribed:ad.subscribed,subscribeText:Gi,subscribeCount:Jh,unsubscribeText:Hi,unsubscribeCount:Ii,enabled:ad.enabled,signinUrl:mf,classic:Xa.useClassicSubscribeButton}:null}
function e(Xa){if(Xa){var Kb=[],eb=Xa.videoId;eb&&Kb.push("v="+eb);(eb=Xa.playlistId)&&Kb.push("list="+eb);(Xa=Xa.startTimeSeconds)&&Kb.push("t="+Xa);return"/watch?"+Kb.join("&")}}
function f(Xa){if(!Xa)return null;var Kb=Xa.simpleText;return Kb?Kb:Xa.runs?g.Pc(Xa.runs,function(eb){return eb.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,r=null,t=null,w=null,x=!1,y=null,D=null,F=null,H=null,M=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,r=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=g.Rb(l,"browseEndpoint","browseId"))w=x,m="/channel/"+w;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):D=f(b.subscribersText)}else"WEBSITE"===
h?((F=g.Rb(l,"urlEndpoint","url"))&&(m=F),n=!0,p="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(M=f(b.additionalFeesText)),(n=g.Rb(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=g.Rb(b,"title","accessibility","accessibilityData","label");var J=b.endpoint?b.endpoint.clickTrackingParams:null,Ka="";if(b.metadata){var va=f(b.metadata);va&&(Ka=va)}return{id:"element-"+c,type:h,title:f(b.title),metadata:Ka,callToAction:f(b.callToAction),
XA:b.image,iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,playlistLength:t,channelId:w,subscribeButton:y,subscribersText:D,isSubscribe:x,targetUrl:m||null,EJ:n,Zc:J?{itct:J}:null,OQ:p,no:a?a:null,HJ:b.isPlaceholder,impressionUrls:D2(b.impressionUrls||[],C2),xJ:D2(b.hovercardShowUrls||[],C2),clickUrls:D2(l.loggingUrls||[],C2),visualElement:g.Fs(b.trackingParams),
productPrice:H,additionalFeesText:M}},E2=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:D2(a.impressionUrls||[],C2),elements:D2(a.elements||[],function(d,e){return GDa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Fs(a.trackingParams));return c},F2=function(a){g.AS.call(this,a);
this.C=this.endscreen=null;this.u={};this.F={};this.D=this.B=null;this.K=[];this.P=!0;this.G=0;a=a.T();this.N=g.iC(a)||g.kC(a);this.events=new g.os(this);g.C(this,this.events);this.events.R(this.player,g.QD("creatorendscreen"),this.oK);this.events.R(this.player,g.RD("creatorendscreen"),this.pK);this.events.R(this.player,"resize",this.Sa);this.events.R(window,"focus",this.JP);this.load();var b=g.Ee("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.$f(this,function(){g.Ie(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},HDa=function(a){return a.player.getVideoData().Kc?"current":a.N?"new":"current"},G2=function(a){return"creator-endscreen-editor"===a.player.T().playerStyle},IDa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",Jf:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=E2(f,HDa(a))));H2(a,f)},
Kh:{v:c},withCredentials:!0};a.N&&(c.Kh.ptype="embedded");var d=b.Er;d&&(c.dc={ad_tracking:d});if(b=g.bG(b))if(b=g.Kc(b),b=g.Gc(b))a.C=g.mq(b,c)},H2=function(a,b,c){c=void 0===c?!0:c;
g.pX(a.player,"creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.q(Object.values(a.u)),e=d.next();!e.done;e=d.next())e.value.dispose();a.u={};a.F={};0<a.K.length&&(a.K.forEach(function(l){l.dispose()}),a.K.length=0);
a.G=0;if((a.endscreen=b)&&b.elements){c&&JDa(a);c=[];d=new g.ND(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.T().u||(a.B=new g.V({I:"div",L:"ytp-ce-shadow"}),g.vP(a.player,a.B.element,4),a.D=new g.gO(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=KDa(a,e);a.u[e.id]=f;a.F[e.id]=e;g.vP(a.player,f.element,4);var h=new g.ND(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);LDa(a,f,e)}g.hN(a.player,
c);a.Sa()}},JDa=function(a){var b=g.Ks(),c=g.Ms();
c&&b&&a.endscreen.visualElement&&g.lt(c,b,a.endscreen.visualElement)},KDa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={I:"div",ha:["ytp-ce-element","ytp-ce-video"],U:{tabindex:"0","aria-label":b.no||"","aria-hidden":"true"},S:[{I:"div",L:"ytp-ce-element-shadow"},{I:"div",L:"ytp-ce-covering-image",U:I2(b)},{I:"div",L:"ytp-ce-covering-shadow-top"},{I:"a",L:"ytp-ce-covering-overlay",U:{href:J2(a,b.targetUrl),tabindex:"-1"},S:[{I:"div",ha:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],U:{dir:g.Hn(b.title||"")},Z:b.title},{I:"div",L:"ytp-ce-video-duration",Z:b.videoDuration||
void 0}]}]};c=new g.V(c);break;case "PLAYLIST":c={I:"div",ha:["ytp-ce-element","ytp-ce-playlist"],U:{tabindex:"0","aria-label":b.no||"","aria-hidden":"true"},S:[{I:"div",L:"ytp-ce-element-shadow"},{I:"div",L:"ytp-ce-covering-image",U:I2(b)},{I:"div",L:"ytp-ce-covering-shadow-top"},{I:"a",L:"ytp-ce-covering-overlay",U:{href:J2(a,b.targetUrl),tabindex:"-1"},S:[{I:"div",ha:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],U:{dir:g.Hn(b.title||"")},Z:b.title},{I:"div",L:"ytp-ce-playlist-count",
S:[{I:"div",L:"ytp-ce-playlist-icon"},{I:"div",L:"ytp-ce-playlist-count-text",Z:b.playlistLength||void 0}]}]}]};c=new g.V(c);break;case "CHANNEL":c={I:"div",ha:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],U:{tabindex:"0","aria-label":b.no||"","aria-hidden":"true"},S:[{I:"div",L:"ytp-ce-element-shadow"},{I:"div",L:"ytp-ce-expanding-overlay",S:[{I:"div",L:"ytp-ce-expanding-overlay-hider"},{I:"div",L:"ytp-ce-expanding-overlay-background"},{I:"div",L:"ytp-ce-expanding-overlay-content",
S:[{I:"div",L:"ytp-ce-expanding-overlay-body",S:[{I:"div",L:"ytp-ce-expanding-overlay-body-padding",S:[{I:"a",ha:["ytp-ce-channel-title","ytp-ce-link"],U:{href:J2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Hn(b.title||"")},Z:b.title},b.subscribeButton?{I:"div",L:"ytp-ce-subscribe-container",S:[{I:"div",L:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",L:"ytp-ce-channel-subscribers-text",Z:b.subscribersText}:"",b.metadata?{I:"div",ha:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],Z:b.metadata}:""]}]}]}]},{I:"div",L:"ytp-ce-expanding-image",U:I2(b)}]};c=new g.V(c);var d=g.oe(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.G(d,"ytp-ce-subscribe-button");if(a.player.T().u){var e=null;var f=b.Zc.itct}else e="endscreen",f=null;e=new g.tY(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.K.push(e)}break;case "WEBSITE":c={I:"div",ha:["ytp-ce-element","ytp-ce-website"],U:{tabindex:"0","aria-label":b.no||"","aria-hidden":"true"},S:[{I:"div",L:"ytp-ce-element-shadow"},{I:"div",L:"ytp-ce-expanding-overlay",S:[{I:"div",L:"ytp-ce-expanding-overlay-hider"},{I:"div",L:"ytp-ce-expanding-overlay-background"},{I:"div",L:"ytp-ce-expanding-overlay-content",S:[{I:"div",L:"ytp-ce-expanding-overlay-body",
S:[{I:"div",L:"ytp-ce-expanding-overlay-body-padding",S:[{I:"div",L:"ytp-ce-website-title",U:{dir:g.Hn(b.title||"")},Z:b.title},{I:"div",L:"ytp-ce-website-metadata",Z:b.metadata},{I:"a",ha:["ytp-ce-website-goto","ytp-ce-link"],U:{href:J2(a,b.targetUrl),target:"_blank",tabindex:"-1"},Z:b.callToAction}]}]}]}]},{I:"div",L:"ytp-ce-expanding-image",U:I2(b)},{I:"div",L:"ytp-ce-expanding-icon",U:MDa(b.iconUrl)}]};c=new g.V(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",L:"ytp-ce-merchandise-price-container",
S:[{I:"div",L:"ytp-ce-merchandise-price",Z:b.productPrice}]},b.additionalFeesText&&c.S.push({I:"div",L:"ytp-ce-merchandise-additional-fees",Z:b.additionalFeesText})),c={I:"div",ha:["ytp-ce-element","ytp-ce-merchandise"],U:{tabindex:"0","aria-label":b.no||"","aria-hidden":"true"},S:[{I:"div",L:"ytp-ce-element-shadow"},{I:"div",L:"ytp-ce-expanding-overlay",S:[{I:"div",L:"ytp-ce-expanding-overlay-hider"},{I:"div",L:"ytp-ce-expanding-overlay-background"},{I:"div",L:"ytp-ce-expanding-overlay-content",
S:[{I:"div",L:"ytp-ce-expanding-overlay-body",S:[{I:"div",L:"ytp-ce-expanding-overlay-body-padding",S:[{I:"div",L:"ytp-ce-merchandise-title",U:{dir:g.Hn(b.title||"")},Z:b.title},c,{I:"div",L:"ytp-ce-merchandise-metadata",Z:b.metadata},{I:"a",ha:["ytp-ce-merchandise-goto","ytp-ce-link"],U:{href:J2(a,b.targetUrl),target:"_blank",tabindex:"-1"},Z:b.callToAction}]}]}]}]},{I:"div",L:"ytp-ce-expanding-image",U:I2(b)},{I:"div",L:"ytp-ce-merchandise-invideo-cta-container",S:[{I:"div",L:"ytp-ce-merchandise-invideo-cta",
Z:b.callToAction||void 0}]}]},c=new g.V(c)}b.HJ&&g.G(c.element,"ytp-ce-placeholder");return c},I2=function(a){if(a.XA)var b=a.XA.thumbnails;
return MDa(b?b[b.length-1].url:null)},MDa=function(a){return a?{style:"background-image: url("+a+")"}:{}},LDa=function(a,b,c){function d(m){m&&(b.va("blur",function(){"none"!=m.style.display&&a.P&&m.focus()}),b.R(m,"focus",f),b.R(m,"blur",h))}
function e(m){a.G+=m;0<a.G?(g.G(b.element,"ytp-ce-force-expand"),K2(a,c.id,!0)):(g.yn(b.element,"ytp-ce-force-expand"),g.yn(b.element,"ytp-ce-element-hover"),K2(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.va("mouseenter",function(){L2(a,b,c)});
b.va("mouseleave",function(){M2(a,b,c)});
a.player.T().u||b.va("click",function(){g.G(b.element,"ytp-ce-element-hover")});
b.va("click",function(m){NDa(a,c,m)});
b.va("keypress",function(m){NDa(a,c,m)});
b.va("focus",function(){L2(a,b,c)});
b.va("blur",function(){M2(a,b,c)});
b.va("touchstart",function(){L2(a,b,c)});
var l=g.qe("ytp-ce-expanding-overlay-hider",b.element);l&&b.R(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.yn(b.element,"ytp-ce-element-hover");g.yn(b.element,"ytp-ce-force-expand")});
b.va("keydown",function(m){a.P=9===m.keyCode&&!m.shiftKey});
d(g.qe("ytp-sb-subscribe",b.element));d(g.qe("ytp-sb-unsubscribe",b.element));b.va("focus",f);b.va("blur",h)},NDa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.wn(d,"ytp-ce-element");){g.wn(d,"subscribe-label")&&N2(a,b);
if(g.wn(d,"ytp-ce-channel-subscribe"))return;d=g.Ke(d)}if(!d||g.wn(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.u[b.id])M2(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.OQ)N2(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Kc(J2(a,b.targetUrl)),c=g.Gc(c),g.PK(c,void 0,b.Zc);else{var e=a.player.getVideoData().Kc,f=function(){var h=J2(a,b.targetUrl),l=b.Zc,m=g.Vp(h);e&&m&&(m.v||m.list)?g.ZW(a.player,m.v,l,m.list,!1):g.OK(h,l)};
N2(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},J2=function(a,b){var c=a.player.T();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.PC(c)+b}else return"";return b},L2=function(a,b,c){g.wn(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.G(b.element,"ytp-ce-element-hover"):a.player.T().u?(new g.E(function(){g.G(b.element,"ytp-ce-element-hover")},200)).start():g.G(b.element,"ytp-ce-element-hover"),O2(a,c.xJ),K2(a,c.id,!0))},M2=function(a,b,c){g.yn(b.element,"ytp-ce-element-hover");
g.yn(b.element,"ytp-ce-force-expand");K2(a,c.id,!1)},K2=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.q(Object.keys(a.u)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.I(a.u[e].element,"ytp-ce-element-shadow-show",c)},O2=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||G2(a))c&&c();else{b=ODa(a,b);var e=0,f=!1,h=new g.E(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.zt(b[a],d)}},N2=function(a,b,c){O2(a,b.clickUrls,c);
(a=g.Ms())&&b.EJ&&g.ot(a,b.visualElement)},ODa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(PDa(b[e],c));return d},PDa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},QDa=function(a){return Array.isArray(a)&&a.length?a[0]:a},P2=function(a){return"string"===typeof a?a:""},Q2=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},RDa=function(a){this.externalId=a},SDa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.u=d},R2=function(a){return a.value?a.value:null},S2=function(a){if(!a)return null;
var b=g.Kc(P2(a.value));b=g.Gc(b);if(!b)return null;var c=Q2(a.target,TDa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new SDa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},UDa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},XDa=function(a){if(!a)return null;
var b=Q2(a.type,VDa),c=Q2(a.trigger,WDa),d=QDa(a.url);d=S2(d?d:null);a=QDa(a.subscribeData);var e=a?a:null;e?(a=P2(e.external_user_id),e=P2(e.subscription_token),a=a&&e?new RDa(a):null):a=null;return b?new UDa(b,c,d,a):null},T2=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},YDa=function(a,b){return g.jb(a.action,b,void 0)},ZDa=function(a,b){this.context=a;
this.u=b},V2=function(a){return a.customMessage?U2("div","iv-card-message",a.customMessage):""},W2=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{I:"div",L:"iv-card-image",U:{style:c},S:d}},X2=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.q(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(U2("li","",c.value));return{I:"ul",L:"iv-card-meta-info",S:b}},U2=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Hn(c);return{I:a,U:b,Z:c}},$Da=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.gr&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.gr+");");c.dir=g.Hn(a.customMessage);var d=[{I:"span",Z:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",L:"iv-card-link-icon"}));return{I:"div",ha:b,U:c,S:d}},Y2=function(a,b,c,d){if(d){b=g.q(b);
for(var e=b.next();!e.done;e=b.next())a.u(e.value,d,c.id,c.Zc,c.yf.click,5)}},aEa=function(a,b){this.merchant=a;
this.price=b},bEa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},cEa=function(a,b){return b?b:bEa(a)?"current":"new"},Z2=function(a,b){g.B.call(this);
var c=this;this.element=a;this.context=b;this.Ja=!1;this.ra=new Map;this.Aa=new Map;this.context.J.addEventListener(g.QD("annotations_module"),function(d){(d=c.ra.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.RD("annotations_module"),function(d){(d=c.Aa.get(d))&&d.apply(c)})},$2=function(a,b,c,d,e,f,h){a.context.u.va(b,"click",function(l){a.Bx(c,d,e,f||[],h||0,l)});
a.context.u.va(b,"touchstart",function(){a.Ja=!1});
a.context.u.va(b,"touchmove",function(){a.Ja=!0})},dEa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},a3=function(a,b,c){return{aC:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
cG:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
uu:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},d3=function(a,b,c){Z2.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.da=this.qb=this.C=this.Fd=!1;this.ia=null;this.cards=[];this.Pa=this.N=this.ea=this.F=this.ka=this.u=null;this.W=[];this.K=this.sd=this.ba=null;this.G=0;this.Y=new g.E(g.Oa,c.D.nd?4E3:3E3);g.C(this,this.Y);this.Ea=new g.E(g.Oa);g.C(this,this.Ea);this.X=new ZDa(c,function(e,f,h,l,m,n){$2(d,e,f,h,l,m,n)});
this.P=new g.V({I:"div",L:"iv-drawer",U:{id:"iv-drawer"},S:[{I:"div",L:"iv-drawer-header",U:{"aria-role":"heading"},S:[{I:"span",L:"iv-drawer-header-text"},{I:"button",ha:["iv-drawer-close-button","ytp-button"],U:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",L:"iv-drawer-content"}]});g.C(this,this.P);this.D=this.P.element;this.za=new g.gO(this.P,330);g.C(this,this.za);this.Qa=g.qe("iv-drawer-header-text",this.D);this.B=g.qe("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.qb&&b3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.qb=d.C)&&c3(d)})},eEa=function(a,b){var c=b.data;
c.autoOpenMs&&a.addCueRange(c.autoOpenMs,0x8000000000000,"",function(){b3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
c.autoCloseMs&&a.addCueRange(c.autoCloseMs,0x8000000000000,"",function(){c3(a)});
var d=c.headerText;g.Me(a.Qa,d);a.N&&a.N.setAttribute("title",d);c.eventId&&(a.eventId=c.eventId);a.ba=g.Fs(c.trackingParams);a.K=g.Fs(c.closeTrackingParams);a.sd=g.Fs(c.iconTrackingParams)},fEa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.G;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.G,type:"simple",teaserText:g.S(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Zc:e3(a,c,b,d),sponsored:!1,yf:a3(d,e,d.command),Ui:d.trackingParams?g.Fs(d.trackingParams):null,Lg:e.trackingParams?g.Fs(e.trackingParams):
null,sd:f&&f.trackingParams?g.Fs(f.trackingParams):null,imageUrl:f3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.S(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,gr:null,title:d.title?g.S(d.title):"",customMessage:d.callToAction?g.S(d.callToAction):"",url:d.command.urlEndpoint.url?S2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};g3(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.G,type:"collaborator",teaserText:g.S(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Zc:e3(a,c,b,d),sponsored:!1,yf:a3(d,e,d.endpoint),Ui:d.trackingParams?g.Fs(d.trackingParams):null,Lg:e.trackingParams?g.Fs(e.trackingParams):null,sd:f&&f.trackingParams?g.Fs(f.trackingParams):
null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.S(d.customText):null,fF:f3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.S(d.channelName):"",metaInfo:[d.subscriberCountText?g.S(d.subscriberCountText):""],url:S2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};g3(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.G,type:"playlist",teaserText:g.S(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Zc:e3(a,c,b,d),sponsored:!1,yf:a3(d,e,d.action),Ui:d.trackingParams?g.Fs(d.trackingParams):null,Lg:e.trackingParams?g.Fs(e.trackingParams):null,sd:f&&f.trackingParams?g.Fs(f.trackingParams):
null,Aq:f3(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.S(d.customMessage):null,playlistVideoCount:g.S(d.playlistVideoCount),title:d.playlistTitle?g.S(d.playlistTitle):"",metaInfo:[d.channelName?g.S(d.channelName):"",d.videoCountText?g.S(d.videoCountText):""],url:S2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:dEa(d.action)})};g3(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.G,type:"video",teaserText:g.S(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Zc:e3(a,c,b,d),sponsored:!1,yf:a3(d,e,d.action),Ui:d.trackingParams?g.Fs(d.trackingParams):null,Lg:e.trackingParams?g.Fs(e.trackingParams):null,sd:f&&f.trackingParams?g.Fs(f.trackingParams):null,Aq:f3(d.videoThumbnail.thumbnails,258).url,
videoDuration:d.lengthString?g.S(d.lengthString):null,customMessage:d.customMessage?g.S(d.customMessage):null,title:d.videoTitle?g.S(d.videoTitle):"",metaInfo:[d.channelName?g.S(d.channelName):"",d.viewCountText?g.S(d.viewCountText):""],isLiveNow:!!d.badge,url:S2({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:dEa(d.action)})};g3(a,c)}a.G++},f3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},e3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},hEa=function(a,b){var c=gEa(a,b);
c&&(c===a.u&&(a.u=null),a.J.removeCueRange(c.card.id),g.Ie(c.Av),g.rb(a.cards,c),a.ir(),h3(a))},b3=function(a,b,c){if(!a.C){a.za.show();
a.ka=new g.E(function(){g.G(a.context.J.getRootNode(),g.q0.IV_DRAWER_OPEN)},0);
a.ka.start();a.ia=g.ap(a.B,"mousewheel",function(h){a.Y.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.Ms();d&&a.ba&&a.K&&g.mt(d,[a.ba,a.K]);b={TRIGGER_TYPE:b};for(var e=g.q(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.GC||(f.GC=!0,iEa(a.context.logger,f.card.yf.aC,b)),d&&g.mt(d,[f.card.Ui]);u2(a.J);c&&(a.F=new g.E(function(){a.ea=a.N;a.Pa.focus()},330),a.F.start())}},c3=function(a){a.C&&(a.za.hide(),g.bp(a.ia),a.ia=null,g.yn(a.context.J.getRootNode(),g.q0.IV_DRAWER_OPEN),a.C=!1,u2(a.J),a.F&&a.F.stop(),a.F=new g.E(function(){a.ea&&(a.ea.focus(),a.ea=null)},330),a.F.start())},kEa=
function(a){g.xn(a.Ma(),[g.q0.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.vP(a.J,a.D,5);jEa(a);a.N=g.qe("ytp-cards-button",a.J.getRootNode());a.Pa=g.qe("iv-drawer-close-button",a.D);a.Fd=!0},jEa=function(a){var b=g.qe("iv-drawer-close-button",a.D);
a.context.u.va(b,"click",a.VH,a);a.context.u.va(a.B,"touchend",function(){a.Y.start()});
a.context.u.va(a.B,"scroll",a.lI,a);a.context.B.subscribe("onHideControls",function(){a.da=!0});
a.context.B.subscribe("onShowControls",function(){a.da=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.da=g.wn(a.J.getRootNode(),"ytp-autohide")});
a.W.push(g.Ko("iv-button-shown",a.LJ,a));a.W.push(g.Ko("iv-button-hidden",a.KJ,a));a.W.push(g.Ko("iv-teaser-shown",a.IK,a));a.W.push(g.Ko("iv-teaser-hidden",a.MJ,a));a.W.push(g.Ko("iv-teaser-clicked",a.HK,a))},g3=function(a,b){a.Fd||kEa(a);
hEa(a,b.id);var c=lEa(a,b);if(c){var d={card:b,Av:c.element,GC:!1},e=mEa(a,d);g.xb(a.cards,e,0,d);c.fa(a.B,e);a.ir();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.u=d,h3(a),nEa(a,d),b3(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&oEa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){oEa(a,d)}),h3(a))}},lEa=function(a,b){switch(b.type){case "simple":var c=a.X;
var d=b.displayDomain?{I:"div",L:"iv-card-image-text",Z:b.displayDomain}:void 0;var e=$Da(b);d={I:"div",ha:["iv-card"],S:[{I:"a",L:"iv-click-target",U:{href:b.url?R2(b.url)||"":""},S:[W2(b.imageUrl,d),{I:"div",L:"iv-card-content",S:[U2("h2",void 0,b.title),e]}]}]};d=new g.V(d);Y2(c,g.pe("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.X,d={I:"div",ha:["iv-card","iv-card-channel"],S:[{I:"a",ha:["iv-click-target"],U:{href:R2(b.url)||"","data-ytid":b.channelId},S:[W2(b.fF),
{I:"div",L:"iv-card-content",S:[V2(b),{I:"h2",L:"iv-card-primary-link",Z:b.title},X2(b)]}]}]},d=new g.V(d),Y2(c,g.pe("iv-click-target",d.element),b,b.url),d;case "playlist":return c=a.X,d={I:"div",ha:["iv-card","iv-card-playlist"],S:[{I:"a",L:"iv-click-target",U:{href:R2(b.url)||""},S:[W2(b.Aq,{I:"div",L:"iv-card-image-overlay",S:[{I:"span",L:"iv-card-playlist-video-count",Z:b.playlistVideoCount}]}),{I:"div",L:"iv-card-content",S:[V2(b),U2("h2","iv-card-primary-link",b.title),X2(b)]}]}]},d=new g.V(d),
Y2(c,g.pe("iv-click-target",d.element),b,b.url),d;case "productListing":c=a.X;var f=!g.ob(b.offers);d=["iv-card"];e="";var h=$Da(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({I:"div",L:"iv-card-offer-price",Z:h.price}),h.merchant&&f.push({I:"div",L:"iv-card-offer-merchant",Z:h.merchant}),h={I:"div",S:f});f=b.url?R2(b.url)||"":"";d={I:"div",ha:d,U:{tabindex:"0"},S:[{I:"a",ha:["iv-card-image","iv-click-target"],U:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{I:"div",L:"iv-card-content",S:[b.sponsored?{I:"div",L:"iv-card-sponsored",S:["Sponsored",{I:"div",L:"iv-ad-info-container",S:[{I:"div",L:"iv-ad-info",Z:"{{adInfo}}"},{I:"div",L:"iv-ad-info-icon-container",S:[{I:"div",L:"iv-ad-info-icon"},{I:"div",L:"iv-ad-info-callout"}]}]}]}:"",{I:"a",L:"iv-click-target",U:{href:f},S:[U2("h2",e,b.title),h]}]}]};d=new g.V(d);e=g.Ee("span");g.Me(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
d.qc(e,"adInfo");Y2(c,g.pe("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.X,d=b.isLiveNow?{I:"span",ha:["yt-badge","yt-badge-live"],Z:"LIVE NOW"}:null,d={I:"div",ha:["iv-card","iv-card-video"],S:[{I:"a",L:"iv-click-target",U:{href:R2(b.url)||""},S:[W2(b.Aq,b.videoDuration?{I:"span",L:"iv-card-video-duration",Z:b.videoDuration}:void 0),{I:"div",L:"iv-card-content",S:[V2(b),U2("h2","iv-card-primary-link",b.title),X2(b),d]}]}]},d=new g.V(d),Y2(c,g.pe("iv-click-target",d.element),
b,b.url),d;default:return null}},mEa=function(a,b){if(0===a.cards.length)return 0;
var c=g.kb(a.cards,function(d){return b.card.startMs>d.card.startMs||b.card.startMs===d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1===c?0:c+1},pEa=function(a){return a.u?"productListing"===a.u.card.type:g.gh(a.cards,function(b){return"productListing"===b.card.type})},h3=function(a){g.I(a.J.getRootNode(),"ytp-cards-shopping-active",pEa(a))},oEa=function(a,b){if(!g.wn(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.u!==b){var c=g.Ms(),d=a.u?a.u.card.sd:a.sd;
c&&d&&g.nt(c,[d]);a.u=b;h3(a)}if(c="none"!=a.Ma().style.display)2===a.context.J.getPresentingPlayerType()?c=1===a.context.J.getAdState():(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=1===c||3===c||d);c&&b.card.teaserDurationMs&&(c={teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs},(d=g.iX(g.$W(a.J)))&&d.wx(!0,c));a.Ea.isActive()||((!a.C||!a.Y.isActive()&&a.da)&&nEa(a,b),a.Ea.start(910+b.card.teaserDurationMs))}},nEa=function(a,b){if(a.P.Xa){var c=new y2([0,
a.B.scrollTop],[0,b.Av.offsetTop],600,ADa);a.context.C.va(c,"animate",function(d){a.B.scrollTop=d.y});
a.context.C.va(c,"finish",function(d){a.B.scrollTop=d.y});
c.play()}else g.xN(a.P,!0),a.B.scrollTop=b.Av.offsetTop,g.xN(a.P,!1)},i3=function(a){return a.u&&a.u.card?a.u.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},gEa=function(a,b){return g.jb(a.cards,function(c){return c.card.id===b})},j3=function(a,b,c){Z2.call(this,a,b);
this.annotation=c;this.isActive=!1},qEa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},k3=function(a,b,c){j3.call(this,a,b,c);
this.B=null;this.K=!1;this.C=null;this.D=!1;this.u=this.G=this.F=null},rEa=function(a,b){var c=void 0===c?0:c;
var d=yDa(b).width;g.tg(b,d);c=new A2(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,zDa);g.C(a,c);a.context.C.va(c,"begin",function(){g.Cg(b,!0)});
c.play()},uEa=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
ha:["iv-branding-context-name"],Z:b.channel_name}),d=a.createElement({I:"div",ha:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.u=new g.tY(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signinUrl,a.context.J),a.u.fa(d));var f=a.createElement({I:"div",ha:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",ha:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Cg(h,!1);var l=a.createElement({I:"div",ha:["branding-context-container-outer"]});l.appendChild(h);g.lg(l,"right",b.image_width+"px");a.Ma().appendChild(l);a.C=new g.E(function(){sEa(a,h,l)},500);
g.C(a,a.C);a.context.u.va(a.Ma(),"mouseover",function(){tEa(a,h,l,f,b.image_height)});
a.context.u.va(a.Ma(),"mouseout",function(){a.C.start()})}},tEa=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.Bg(b);a.u||(b.style.width=g.sg(f.width,!0),c.style.width=g.sg(f.width,!0));g.lg(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.lg(d,"right","1px");a.D=!0;g.Cg(b,!0);a.F=new g.E(function(){g.G(this.Ma(),"iv-branding-active")},0,a);
a.F.start()}},sEa=function(a,b,c){g.yn(a.Ma(),"iv-branding-active");
a.G=new g.E(function(){g.Cg(b,!1);a.u||(c.style.width=g.sg(0,!0))},250);
a.G.start();a.D=!1},vEa=function(a,b,c,d,e,f,h){this.u=a;
this.C=b;this.D=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},l3=function(a,b,c){j3.call(this,a,b,c);
var d=this;this.N=this.isCollapsed=this.P=!1;this.G=5E3;this.B=this.C=this.u=this.D=null;this.K=this.createElement({I:"div",ha:["iv-promo-contents"]});this.F=new g.E(function(){d.u.setAttribute("aria-hidden","true");g.Cg(d.C,!1);g.Cg(d.B,!0)},700,this);
g.C(this,this.F)},wEa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.G=b.collapsedelay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.Ma().setAttribute("aria-hidden","true");a.Ma().setAttribute("aria-label","Promotion");a.Ma().tabIndex=0;var e=a.annotation.rd(),f=b.image_url;if(f){var h=a.createElement({I:"div",ha:["iv-promo-img","iv-click-target"]});f=a.createElement({I:"img",U:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?
(f=a.createElement({I:"span",L:"iv-promo-video-duration",Z:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({I:"span",L:"iv-promo-playlist-length",Z:b.playlist_length.toString()}),h.appendChild(f));e&&$2(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({I:"a",L:"iv-promo-txt"}),g.id(f,R2(e)),a.u=f):a.u=a.createElement({I:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({I:"p",S:[{I:"strong",Z:b.text_line_1}]});
var m=a.createElement({I:"p",S:[{I:"span",L:"iv-promo-link",Z:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({I:"button",ha:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({I:"button",ha:["iv-button","iv-promo-button"],S:[{I:"span",L:"iv-button-content",Z:f}]});var p=a.createElement({I:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&$2(a,a.Ma(),e,a.annotation.id,b.session_data,void 0,c)}g.G(a.u,"iv-click-target");
e&&$2(a,a.u,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({I:"p",S:[{I:"span",Z:b.text_line_1}]}),m=a.createElement({I:"p",S:[{I:"strong",Z:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({I:"span",ha:["yt-badge","iv-promo-badge-live"],Z:"LIVE NOW"})),g.G(a.u,"iv-click-target"),e&&$2(a,a.u,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.u.appendChild(l);m&&a.u.appendChild(m);a.K.appendChild(a.u);p&&a.K.appendChild(p);c=
a.createElement({I:"div",L:"iv-promo-actions"});a.B=a.createElement({I:"button",ha:["iv-promo-expand","ytp-button"]});a.B.title="Expand";a.context.u.va(a.B,"click",function(r){m3(a,5E3,r)});
c.appendChild(a.B);g.Cg(a.B,!1);a.context.u.va(a.Ma(),"mouseover",a.eJ,a);a.context.u.va(a.Ma(),"mouseout",a.dJ,a);a.context.u.va(a.Ma(),"touchend",function(r){m3(a,5E3,r)});
a.C=a.createElement({I:"button",ha:["iv-promo-close","ytp-button"]});a.C.title="Close";a.context.u.va(a.C,"click","cta"===a.annotation.style&&b.text_line_3?a.XI:a.WI,a);c.appendChild(a.C);g.xn(a.Ma(),d);h&&(a.Ma().appendChild(h),n&&h.appendChild(n));a.Ma().appendChild(a.K);a.Ma().appendChild(c)},m3=function(a,b,c){c.stopPropagation();
xEa(a);yEa(a,b);a.u.focus()},zEa=function(a){a.isCollapsed||a.N||a.D||(g.G(a.Ma(),"iv-promo-collapsed"),a.isCollapsed=!0,a.F.start())},xEa=function(a){a.F.stop();
a.isCollapsed&&(g.zn(a.Ma(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.u&&a.u.removeAttribute("aria-hidden"),g.Cg(a.B,!1),g.Cg(a.C,!0))},yEa=function(a,b){a.D||(a.D=g.Rm(function(){n3(this);
zEa(this)},b,a))},n3=function(a){a.D&&(g.v.clearTimeout(a.D),a.D=null)},AEa=function(a){this.J=a},iEa=function(a,b,c){b&&(c?o3(a,b.map(function(d){return g.ln(d,c)})):o3(a,b))},o3=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.q(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.zt(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},p3=function(a){g.AS.call(this,a);
var b=this;this.P=!1;this.loadNumber=0;this.K={};this.logger=new AEa(this.player);this.F=new g.os(this);this.G=this.C=null;this.events=new g.os(this);this.N=this.u=null;this.W=[];g.C(this,this.F);this.F.R(this.player,"onVideoAreaChange",function(){b.V("onVideoAreaChange")});
this.F.R(this.player,"onHideControls",function(){b.V("onHideControls")});
this.F.R(this.player,"onShowControls",function(){b.V("onShowControls")});
this.F.R(this.player,"resize",function(d){b.V("resize",d)});
this.F.R(this.player,"presentingplayerstatechange",function(d){b.V("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.GK,this);this.subscribe("resize",this.Pt,this);this.player.T().K.subscribe("vast_info_card_add",this.NE,this);g.C(this,this.events);this.X=this.createElement({I:"div",L:"video-custom-annotations"});this.B=new g.V({I:"div",ha:["ytp-player-content","ytp-iv-player-content"]});g.C(this,this.B);g.vP(this.player,this.B.element,4);this.B.hide();this.D=new g.V({I:"div",ha:["ytp-iv-video-content"]});g.C(this,this.D);a=this.createElement({I:"div",L:"video-annotations"});
a.appendChild(this.X);this.D.element.appendChild(a);BEa(this)&&this.load();var c=this.createElement({I:"style"});(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(c);g.$f(this,function(){g.Ie(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},CEa=function(a){a=a.createElement({I:"div",
ha:["annotation","annotation-type-custom"]});g.Cg(a,!1);return a},BEa=function(a){var b=a.player.T();
a=a.player.getVideoData();return 1===(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.HG||b.K.get(a.videoId)||g.dG(a)||g.eG(a)?!0:!1},DEa=function(a,b){var c=!b.isCued()&&!g.U(b,1024);
g.xN(a.B,c);g.xN(a.D,c)},EEa=function(a,b,c){a.P=!0;
a.G=g.mq(b,c)},FEa=function(a,b){for(var c={},d=g.q(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Sa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(FEa(a,e))}return c},IEa=function(a){var b=a.player.getVideoData();
if(b.rg){var c=a.player.T().K.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.gq(h)&&h.responseXML?h.responseXML:null)&&q3(a,h)}};
g.qp()&&(d.onFinish=GEa(a,d.onFinish));d.postParams={ic_only:"1"};HEa(d,c);a.P=!0;g.mq(b.rg,d)}}},HEa=function(a,b){a.method="POST";
a.dc=a.dc||{};b.zo&&(a.dc.ic_coll=b.zo);b.qr&&(a.dc.ic_xml=b.qr);b.Eq&&(a.dc.ic_track=b.Eq)},JEa=function(a){var b=new g.V({I:"div"});
g.Cg(b.element,!1);var c=new d3(a.player,b.element,r3(a));g.C(c,b);b.fa(a.B.element);c.lq();return c},r3=function(a){if(!a.N){var b=new B2(a);
g.C(a,b);var c=new g.l1(a);g.C(a,c);a.N=new vEa(b,c,a.player.T(),a.player.getVideoData(),a.logger,a.player,a.qb)}return a.N},q3=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Ms();if(e){var f=g.Ks();f&&g.et(g.so("use_default_events_client")?void 0:g.zr,e,f,[g.Fs(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var h=FEa(a,d[e]);f=null;try{if(h){var l=h.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var p=Q2(h.type,KEa),r=Q2(h.style,LEa),t=P2(h.data),w=0!==t.length?JSON.parse(t):{};var x=h.action;h=XDa;if(null==x)var y=null;else if(g.Ra(x)){m=[];for(var D=g.q(x),F=D.next();!F.done;F=
D.next()){var H=h(F.value);H&&m.push(H)}y=m}else{var M=h(x);y=M?[M]:[]}f=n&&p?new T2(n,p,r,y,w):null}else f=null}catch(eb){}if(f)if("branding"===f.type||"promotion"===f.type){h=a;m=f;var J=CEa(h),Ka=null;switch(m.type){case "branding":if(h.player.T().bb)break;h.B.element.appendChild(J);Ka=new k3(J,r3(h),m);break;case "promotion":g.vP(h.player,J,4),Ka=new l3(J,r3(h),m)}Ka&&Ka.lq();if(h=Ka)g.C(a,h),a.K[f.id]=h}else if("card"===f.type||"drawer"===f.type){a.u||(a.u=JEa(a),g.C(a,a.u));if("card"===f.type){c=
a.u;var va=f&&f.data&&f.data.card_type;h=f.data;if(va)switch(m=h.tracking||{},m={aC:m.impression,click:m.click,close:m.close,cG:m.teaser_impression,uu:m.teaser_click},J=h.tracking_params||{},Ka=null,va){case "collaborator":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Zc:h.session_data||{},sponsored:h.sponsored||!1,yf:m,Ui:J.card?g.Fs(J.card):null,Lg:J.teaser?g.Fs(J.teaser):null,sd:J.icon?
g.Fs(J.icon):null,channelId:h.channel_id,customMessage:h.custom_message?h.custom_message:null,fF:h.image_url,title:h.title,metaInfo:h.meta_info,url:S2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};g3(c,f);break;case "playlist":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Zc:h.session_data||{},sponsored:h.sponsored||!1,yf:m,Ui:J.card?g.Fs(J.card):null,
Lg:J.teaser?g.Fs(J.teaser):null,sd:J.icon?g.Fs(J.icon):null,Aq:h.image_url,playlistVideoCount:h.playlist_video_count,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,url:S2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};g3(c,f);break;case "productListing":h.signin_url&&(Ka=S2({target:"current",value:h.signin_url}));va=[];for(var Xa=h.offers||[],Kb=0;Kb<Xa.length;Kb++)va.push(new aEa(g.od(Xa[Kb].merchant),g.od(Xa[Kb].price)));
f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Zc:h.session_data||{},sponsored:h.sponsored||!1,yf:m,Ui:J.card?g.Fs(J.card):null,Lg:J.teaser?g.Fs(J.teaser):null,sd:J.icon?g.Fs(J.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,gr:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:
null,url:S2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url}),s4:Ka,r4:h.signin_title?h.signin_title:void 0,q4:h.signin_message?h.signin_message:void 0,offers:va};g3(c,f);break;case "simple":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Zc:h.session_data||{},sponsored:h.sponsored||!1,yf:m,Ui:J.card?g.Fs(J.card):null,Lg:J.teaser?g.Fs(J.teaser):null,sd:J.icon?
g.Fs(J.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,gr:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:null,url:S2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};g3(c,f);break;case "video":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||
!1,Zc:h.session_data||{},sponsored:h.sponsored||!1,yf:m,Ui:J.card?g.Fs(J.card):null,Lg:J.teaser?g.Fs(J.teaser):null,sd:J.icon?g.Fs(J.icon):null,Aq:h.image_url,videoDuration:h.video_duration||null,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,isLiveNow:!!h.is_live_now,url:S2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})},g3(c,f)}}else eEa(a.u,f);c=!0}}c&&(u2(a.player),a.Pt())},MEa=function(a,b){var c=!1;
a.u||(a.u=JEa(a),g.C(a,a.u));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(fEa(a.u,e.cardRenderer),c=!0);c&&(c=a.u,d=b.headerText?g.S(b.headerText):"",g.Me(c.Qa,d),c.N&&c.N.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.ba=b.trackingParams?g.Fs(b.trackingParams):null,c.K=b.closeButton.infoCardIconRenderer.trackingParams?g.Fs(b.closeButton.infoCardIconRenderer.trackingParams):null,c.sd=b.icon.infoCardIconRenderer.trackingParams?
g.Fs(b.icon.infoCardIconRenderer.trackingParams):null,u2(a.player),a.Pt())},NEa=function(a,b,c,d,e){if(!a.player.T().bb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new UDa("openUrl","click",new SDa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.S(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.S(b.subscriberCountText))):(b.subscriberCountText&&(e=g.S(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.S(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.S(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.S(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new T2(c,"branding","branding",f,d);l=CEa(a);a.B.element.appendChild(l);f=new k3(l,r3(a),f);f.lq();g.C(f,f);a.K[c]=f}},GEa=function(a,b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.la()||(d.unshift(b),b=g.Va.apply(window,d),a.W.push(g.op(b)))}},OEa=function(a){return"annotation-editor"===a||"live-dashboard"===a},v2={},w2=null;g.Ya(y2,g.Bn);g.k=y2.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.Ha)this.progress=0,this.coords=this.u;else if(this.Jb())return!1;x2(this);this.startTime=a=g.A();-1==this.Ha&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.Nt();this.ug("play");-1==this.Ha&&this.ug("resume");this.Ha=1;var b=g.Ua(this);b in v2||(v2[b]=this);CDa();DDa(this,a);return!0};
g.k.stop=function(a){x2(this);this.Ha=0;a&&(this.progress=1);EDa(this,this.progress);this.ug("stop");this.Op()};
g.k.pause=function(){this.Jb()&&(x2(this),this.Ha=-1,this.ug("pause"))};
g.k.aa=function(){0==this.Ha||this.stop(!1);this.ug("destroy");y2.od.aa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.Aw=function(){this.ug("animate")};
g.k.ug=function(a){this.dispatchEvent(new FDa(a,this))};
g.Ya(FDa,g.Il);g.Ya(z2,y2);z2.prototype.C=g.Oa;z2.prototype.Aw=function(){this.C();z2.od.Aw.call(this)};
z2.prototype.Op=function(){this.C();z2.od.Op.call(this)};
z2.prototype.Nt=function(){this.C();z2.od.Nt.call(this)};
g.Ya(A2,z2);A2.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.u(B2,g.B);B2.prototype.va=function(a,b,c,d){c=(0,g.z)(c,d||this.B);a=g.ap(a,b,c);this.u.push(a);return a};
B2.prototype.Ps=function(a,b,c,d){c=(0,g.z)(c,d||this.B);a=g.jp(a,b,c);this.u.push(a);return a};
B2.prototype.Db=function(a){g.bp(a);g.rb(this.u,a)};
B2.prototype.aa=function(){g.bp(this.u);this.u.length=0;g.B.prototype.aa.call(this)};g.u(F2,g.AS);g.k=F2.prototype;g.k.load=function(){g.AS.prototype.load.call(this);if(!G2(this)){var a=g.cG(this.player.getVideoData());a?(a=E2(a,HDa(this)),H2(this,a,!1)):IDa(this)}};
g.k.unload=function(){H2(this,null);this.C&&(this.C.abort(),this.C=null);g.AS.prototype.unload.call(this)};
g.k.je=function(a,b){if(!G2(this))return null;if("loadCustomEndscreenRenderer"===a){var c=E2(b,"new");H2(this,c);return!0}return null};
g.k.getOptions=function(){return G2(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Sa=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<PEa.length;f++){var h=Math.abs(b.width-PEa[f]);if(-1===e||d>=h)e=f,d=h}d=QEa[e];this.B&&g.lg(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.u[f],
h=this.F[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Ag(e.element,Math.round(h.width*a.width),f);g.tg(e.element,m,n);g.zn(e.element,REa);m=h.left+h.width/2;h=h.top+l/2;g.G(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.zn(e.element,QEa);g.G(e.element,d);(e=g.oe(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.lg(e,"height",f+"px")}}}}};
g.k.oK=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())O2(this,this.endscreen.impressionUrls),(a=g.Ms())&&this.endscreen.visualElement&&g.ft(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.u[a],c=this.F[a];g.G(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.G(b,"ytp-ce-shown");O2(this,c.impressionUrls);(b=g.Ms())&&g.ft(b,c.visualElement,void 0);this.player.T().C&&this.player.xa("endscreenelementshown",
a)}};
g.k.pK=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.u[a];g.yn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.yn(b,"ytp-ce-shown");this.player.T().C&&this.player.xa("endscreenelementhidden",a)}};
g.k.JP=function(a){var b=this;a.target===window&&(new g.E(function(){for(var c=g.q(Object.values(b.u)),d=c.next();!d.done;d=c.next())g.zn(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var PEa=[346,426,470,506,570,640,853,1280,1920],QEa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),REa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var TDa={MU:"current",h_:"new"};var VDa={CLOSE:"close",s_:"openUrl",vH:"subscribe"},WDa={SS:"click",CLOSE:"close",iW:"hidden",J0:"rollOut",K0:"rollOver",w1:"shown"};T2.prototype.rd=function(){var a=YDa(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var LEa={pS:"anchored",ZG:"branding",CHANNEL:"channel",LU:"cta",lW:"highlightText",jX:"label",PLAYLIST:"playlist",h0:"popup",F1:"speech",vH:"subscribe",h2:"title",VIDEO:"video",r3:"website"},KEa={ZG:"branding",IS:"card",aV:"drawer",kW:"highlight",GY:"marker",r0:"promotion",TEXT:"text",z3:"widget"};g.u(Z2,g.B);g.k=Z2.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.ND(a,b,{id:c});a.namespace="annotations_module";d&&this.ra.set(a,d);e&&this.Aa.set(a,e);g.hN(this.context.J,[a])};
g.k.lq=function(){this.context.B.subscribe("resize",this.ir,this)};
g.k.Ma=function(){return this.element};
g.k.Bx=function(a,b,c,d,e,f){if(this.Ja)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Ie(this.Ma())};
g.k.ir=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=R2(a);if(f){var h=cEa(f,a.target),l=function(){a.u&&e.context.J.pauseVideo();var m=e.context.videoData.Kc||!1,n=g.Vp(f||"");m&&n&&(n.v||n.list)?g.YW(e.context.J.app,n.v,b,n.list,!1,void 0):g.PK(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);o3(this.context.logger,c,l,d);bEa(f)||(c=g.Ms(),d=b.itct,c&&d&&g.ot(c,g.Fs(d)))}};
g.k.aa=function(){this.ra.clear();this.Aa.clear();g.B.prototype.aa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.C(this,a);return a.element};g.u(d3,Z2);g.k=d3.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.Bg(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.ir=function(){var a=this.isAvailable();g.Cg(this.Ma(),a);g.I(this.context.J.getRootNode(),g.q0.IV_DRAWER_ENABLED,a);u2(this.J)};
g.k.destroy=function(){var a=g.iX(g.$W(this.J));a&&a.wx(!1,void 0);try{this.J.getRootNode().removeChild(this.D)}catch(b){}g.Lo(this.W);g.bp(this.ia);this.ka&&this.ka.dispose();this.F&&this.F.dispose();Z2.prototype.destroy.call(this)};
g.k.VH=function(){if(this.C){o3(this.context.logger,i3(this).yf.close);var a=g.Ms();a&&this.K&&g.ot(a,this.K);c3(this)}};
g.k.lI=function(){g.I(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.LJ=function(){var a=g.Ms(),b=i3(this);b=b?b.sd:this.sd;a&&b&&g.mt(a,[b])};
g.k.KJ=function(){var a=g.Ms(),b=i3(this);b=b?b.sd:this.sd;a&&b&&g.nt(a,[b])};
g.k.IK=function(){var a=i3(this);o3(this.context.logger,a.yf.cG);var b=g.Ms();b&&a&&g.mt(b,[a.Lg,a.sd])};
g.k.MJ=function(){var a=g.Ms(),b=i3(this);a&&b&&g.nt(a,[b.Lg])};
g.k.HK=function(a){var b=i3(this),c=g.Ms();this.u?a?(a=this.context.logger,o3(a,b.yf.uu),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Lg&&g.ot(c,b.Lg)):(a=this.context.logger,o3(a,b.yf.uu),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.sd&&g.ot(c,b.sd)):(a=this.context.logger,o3(a,b.yf.uu),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.sd&&g.ot(c,this.sd))};g.u(j3,Z2);j3.prototype.lq=function(){Z2.prototype.lq.call(this);qEa(this)};
j3.prototype.show=function(){Z2.prototype.show.call(this);var a=g.Ms(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.mt(a,[g.Fs(b.itct)])};
j3.prototype.hide=function(){Z2.prototype.hide.call(this);var a=g.Ms(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.nt(a,[g.Fs(b.itct)])};g.u(k3,j3);
k3.prototype.show=function(){if(!this.isActive){j3.prototype.show.call(this);if(!this.K){g.G(this.Ma(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",ha:["branding-img","iv-click-target"],U:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Cg(this.B,!1);var b=this.createElement({I:"div",ha:["branding-img-container"]});b.appendChild(this.B);this.Ma().appendChild(b);(b=this.annotation.rd())&&$2(this,this.B,b,this.annotation.id,a.session_data);
uEa(this,a);this.K=!0}g.Cg(this.Ma(),!0);this.isActive=!0;this.B&&rEa(this,this.B)}};
k3.prototype.hide=function(){this.isActive&&(j3.prototype.hide.call(this),g.Cg(this.Ma(),!1),this.isActive=!1)};
k3.prototype.destroy=function(){this.u&&(this.u.dispose(),this.u=null);j3.prototype.destroy.call(this)};g.u(l3,j3);g.k=l3.prototype;g.k.show=function(){this.isActive||(j3.prototype.show.call(this),this.P||(wEa(this),this.P=!0),g.Cg(this.Ma(),!0),g.Rm(function(){g.yn(this.Ma(),"iv-promo-inactive")},100,this),this.Ma().removeAttribute("aria-hidden"),this.isActive=!0,n3(this),xEa(this),yEa(this,this.G))};
g.k.hide=function(){this.isActive&&(g.G(this.Ma(),"iv-promo-inactive"),this.isActive=!1,this.Ma().setAttribute("aria-hidden","true"))};
g.k.Bx=function(a,b,c,d,e,f){return this.isCollapsed?!1:j3.prototype.Bx.call(this,a,b,c,d,e,f)};
g.k.eJ=function(a){this.N=!0;m3(this,500,a)};
g.k.dJ=function(){this.N=!1;zEa(this)};
g.k.WI=function(a){a.stopPropagation();this.hide()};
g.k.XI=function(a){a.stopPropagation();n3(this);this.isCollapsed=!0;g.G(this.Ma(),"iv-promo-collapsed-no-delay");this.F.start()};
g.k.destroy=function(){this.F.dispose();j3.prototype.destroy.call(this)};g.u(p3,g.AS);g.k=p3.prototype;g.k.je=function(a,b){if(!OEa(this.player.T().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.k1(b);c&&q3(this,c);return!0;case "removeCustomAnnotationById":return b&&this.u&&(hEa(this.u,b),u2(this.player)),!0}return null};
g.k.getOptions=function(){return OEa(this.player.T().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Pt=function(){if(this.D){var a=g.KG(this.player).getVideoContentRect(!0);g.Ag(this.D.element,a.width,a.height);g.tg(this.D.element,a.left,a.top)}if(this.u){var b=this.player.di();a=this.u;b=b.width;g.I(a.D,"iv-drawer-small",426>=b);g.I(a.D,"iv-drawer-big",1280<=b)}};
g.k.GK=function(a){DEa(this,a.state);g.U(a.state,2)&&(this.yp()&&this.TC()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.wx(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.gq(h)&&h.responseXML?h.responseXML:null)&&(q3(b,h),g.G(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.AS.prototype.load.call(this);DEa(this,g.tJ(this.player));this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.qp()&&(a=GEa(this,a));var e={format:"XML",Jf:a,onError:function(){b.G=null},
Kh:{}};c.isPharma&&(e.Kh.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.T().K.get(d);f&&HEa(e,f);f=f&&(f.qr||f.zo);if(!c.Zq||f)c.rg?EEa(this,c.rg,e):(this.C=function(){b.Na(e)},this.player.addEventListener("videodatachange",this.C));
g.vP(this.player,this.D.element,4);this.Pt();(f=g.dG(c))&&MEa(this,f);(f=g.eG(c))&&f.featuredChannel&&NEa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.Na=function(a){var b=this.player.getVideoData();b.rg&&(this.C&&(this.player.removeEventListener("videodatachange",this.C),this.C=null),EEa(this,b.rg,a))};
g.k.unload=function(){g.pX(this.player,"annotations_module");for(var a=g.q(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.N=null;this.u&&(this.u.destroy(),this.u=null,u2(this.player));this.P=!1;this.G&&(this.G.abort(),this.G=null);this.K={};this.B.hide();g.AS.prototype.unload.call(this);this.D.detach();this.C&&(this.player.removeEventListener("videodatachange",this.C),this.C=null)};
g.k.NE=function(a){a===this.player.getVideoData().videoId&&(this.loaded?IEa(this):this.load())};
g.k.yp=function(){return!!this.u&&this.u.isAvailable()};
g.k.TC=function(){this.yp();return!!this.u&&this.u.C};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.yp();this.u&&(a?c?b3(this.u,c,b):b3(this.u,"YOUTUBE_DRAWER_AUTO_OPEN",b):c3(this.u))};
g.k.wx=function(a,b){this.player.V(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.aa=function(){this.player.T().K.unsubscribe("vast_info_card_add",this.NE,this);g.yn(this.player.getRootNode(),g.q0.IV_DRAWER_OPEN);for(var a=this.W,b=0,c=a.length;b<c;b++)g.rp(a[b]);this.W.length=0;g.AS.prototype.aa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.C(this,a);return a.element};g.DX.annotations_module=p3;g.DX.creatorendscreen=F2;})(_yt_player);
