(function(g){var window=this;var v3=function(a){var b={languageCode:a.languageCode,languageName:a.languageName,displayName:g.SE(a),kind:a.kind,name:a.name,id:a.id,is_servable:a.u,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.vssId};a.translationLanguage&&(b.translationLanguage=a.translationLanguage);return b},w3=function(a){return a.translationLanguage?a.translationLanguage.languageCode:a.languageCode},SEa=function(a,b){var c=new g.RE;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.u=a.u;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},TEa=function(){this.B=[];
this.u=[]},x3=function(a,b){switch(b.kind){case "asr":UEa(b,a.B);
break;default:UEa(b,a.u)}},UEa=function(a,b){g.jb(b,function(c){return c?a.toString()===c.toString():!1})||b.push(a)},y3=function(){g.B.call(this);
this.B=new TEa;this.D=[]},z3=function(a,b,c){y3.call(this,a);
this.audioTrack=c;this.u=null;this.D=b.yv},A3=function(){this.segments=[]},VEa=function(a,b){var c=g.Ab(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.qb(a.segments,c),g.qb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.xb(a.segments,c,0,b),g.xb(a.segments,c+1,0,b)))},B3=function(a,b,c,d,e,f){g.B.call(this);
this.policy=a;this.player=b;this.W=c;this.G=d;this.F=e;this.N=f;this.P=this.player.T();this.D=new A3;this.B=this.C=this.u=null;this.K=new g.E(this.EC,1E3,this);this.events=new g.os(this);g.C(this,this.K);g.C(this,this.events);this.events.R(b,"SEEK_COMPLETE",this.iD);this.iD();this.EC()},WEa=function(a,b){var c=g.cw(b,a.policy,{}).rd(),d={format:"RAW",
withCredentials:!0};a.F&&(d.responseType="arraybuffer");a.B=g.Sr(c,d,3,100).then(function(e){a:{a.la();if(a.C){var f=!(a.F?e.response:e.responseText)||400<=e.status,h=g.Zz(e);if(h){e=g.cw(a.C,a.policy,{});f=a.C;g.Zv(f.B,e,h);f.requestId=e.get("req_id");WEa(a,a.C);break a}f||null==a.G||(h=a.C.u[0],a.F?a.G(e.response,1E3*(h.startTime+a.player.oc())):a.G(e.responseText,1E3*(h.startTime+a.player.oc())))}a.C=null;a.B=null}});
a.C=b;VEa(a.D,a.C.u[0].B)},C3=function(a,b){y3.call(this,b.T());
this.ma=a;this.J=b;this.u=null;this.C=!1;this.F=g.EC(this.J.T())&&!this.ma.isManifestless},XEa=function(a,b){var c=[],d;
for(d in a.ma.u)if(a.ma.u.hasOwnProperty(d)){var e=a.ma.u[d];if(g.yX(e,b||null)){var f="en",h="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;c.push(new g.RE({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},YEa=function(a,b){return null!=b&&b in a.ma.u?a.ma.u[b]:null},ZEa=function(a,b,c){var d=[],e;
for(e in a.ma.u)if(a.ma.u.hasOwnProperty(e)){var f=a.ma.u[e];if(g.yX(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},D3=function(a,b,c,d,e){y3.call(this,e||null);
this.videoId=b;this.bC=d;this.F={};this.u=null;b=c||g.Vp(a).hl||"";b=b.split("_").join("-");this.C=g.Xp(a,{hl:b})},E3=function(a,b,c,d,e,f,h){var l={};
g.Wa(l,b);g.Wa(l,a.params);g.Wa(l,c);var m={};g.Wa(m,b.sc);a.params.sc&&g.Wa(m,a.params.sc);g.Wa(m,c.sc);l.sc=m;g.V.call(this,{I:"div",L:"caption-window",U:{id:"caption-window-"+a.id,dir:1===l.u?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:l.lang},S:[{I:"span",L:"captions-text",U:{style:"word-wrap: normal; display: block;"}}]});this.F=[];this.Y=!1;this.B=a;this.ea=this.ba=null;this.playerWidth=e;this.playerHeight=f;this.experiments=h;this.G=null;this.maxWidth=.96*e;this.Ja=.96*f;this.u=l;
this.bb=c;this.D=this.ga("captions-text");this.Qa=""!==this.D.style.getPropertyValue("box-decoration-break")||""!==this.D.style.getPropertyValue("-webkit-box-decoration-break");this.da=d/360*16;this.type=0;this.ra=this.da*$Ea(m);a=new g.vs(this.element,!0);g.C(this,a);a.subscribe("dragstart",this.QK,this);a.subscribe("dragmove",this.PK,this);a.subscribe("dragend",this.OK,this);this.Ea=this.za=0;b="";this.u.windowOpacity&&(a=g.j1(this.u.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.u.windowOpacity+
")");a={"background-color":b,display:!1===this.u.isVisible?"none":"","text-align":aFa[this.u.textAlign]};this.Qa&&(a["border-radius"]=b?this.ra/8+"px":"");if(this.C=2===this.B.params.u||3===this.B.params.u)b=this.element,c="vertical-rl",1===this.u.C&&(c="vertical-lr"),g.xe&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.lg(b,"-o-writing-mode",c),g.lg(b,"-webkit-writing-mode",c),g.lg(b,"writing-mode",c),g.lg(b,"text-orientation","upright"),g.G(b,"ytp-vertical-caption"),3===this.B.params.u&&(g.lg(b,"text-orientation",
""),g.lg(b,"transform","rotate(180deg)"));g.lg(this.element,a);switch(this.u.Qg){case 0:case 1:case 2:g.G(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.G(this.element,"ytp-caption-window-bottom")}},$Ea=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},bFa=function(a,b){var c={},d=b.background?b.background:a.u.sc.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.u.sc.backgroundOpacity;d=g.j1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Qa&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ra/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.da*$Ea(b)+"px";d=1;e=b.color||a.u.sc.color;if(b.color||null!=b.textOpacity)e=g.j1(e),d=null==b.textOpacity?a.u.sc.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.Dv&&(h=e=b.Dv);var l=a.da/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Xj()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.u.sc.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.ih&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.wJ&&(c.visibility="hidden");1===b.XB&&a.C&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.JC||g.KC,3===a.B.params.u?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Eh||2===b.Eh||3===b.Eh||4===b.Eh||5===b.Eh)if(g.JC)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Eh){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},cFa=function(a){a.G=g.Ee("SPAN");
g.lg(a.G,{display:"block"});g.G(a.G,"caption-visual-line");a.D.appendChild(a.G)},dFa=function(a,b){var c=g.Ee("SPAN");
g.lg(c,{display:"inline-block","white-space":"pre-wrap"});g.lg(c,bFa(a,b));c.classList.add("ytp-caption-segment");a.G.appendChild(c);c.previousElementSibling&&(g.lg(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.lg(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},eFa=function(a,b,c){a.Y=a.Y||!!c;
var d={};g.Wa(d,a.u.sc);g.Wa(d,c||b.u);g.Wa(d,a.bb.sc);(c=!a.G)&&cFa(a);for(var e=a.ba&&a.ea&&g.Yb(d,a.ea)?a.ba:dFa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(cFa(a),e=dFa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Fe(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.JC||!g.pg(n.children[2],"text-emphasis")||(m=a.C?"padding-right":"padding-top",g.pg(n.children[2],"text-emphasis-position")&&(m=a.C?"padding-left":"padding-bottom"),
g.ze?g.lg(e,m,"1em"):g.lg(e,m,"0.5em")))}a.ea=d;a.ba=e;a.F.push(b)},F3=function(a,b,c,d,e,f,h){E3.call(this,a,b,c,d,e,f,h);
this.type=1},G3=function(a,b,c,d,e,f,h){E3.call(this,a,b,c,d,e,f,h);
this.type=2;this.K=[];this.W=this.P=this.ia=0;this.X=NaN;this.Pa=0;this.qb=null;this.ka=new g.E(this.PO,433,this);g.G(this.element,"ytp-caption-window-rollup");g.C(this,this.ka);g.lg(this.element,"overflow","hidden")},fFa=function(a,b){return(a.C?b.offsetHeight:b.offsetWidth)+1},gFa=function(a){if(isNaN(a.X)){var b=a.u.Wj;
if(b){var c=g.Ee("SPAN");g.Me(c,"\u2013".repeat(b));g.lg(c,bFa(a,a.u.sc));a.D.appendChild(c);a.X=c.offsetWidth;a.D.removeChild(c)}else a.X=0}return a.X},hFa=function(a,b){if(!b)return"";
a.C&&1!==a.B.params.C&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},iFa=function(a){a.K=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.B.params.B,c=0,d=0,e=a.K.length-1;c<b&&-1<e;){var f=a.K[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.K.length<b&&(d*=b/a.K.length);a.P=d;a.W=Math.max(gFa(a),a.Pa,fFa(a,a.D))},jFa=function(a,b){iFa(a);
var c=a.K.reduce(function(e,f){return(a.C?f.offsetWidth:f.offsetHeight)+e},0);
c=a.P-c;if(c!==a.ia){var d=0<c&&0===a.ia;b||isNaN(c)||d||(g.G(a.element,"ytp-rollup-mode"),a.ka.Gb());g.lg(a.D,"transform",hFa(a,c));a.ia=c}iFa(a)},H3=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.ND.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.u=h},I3=function(a,b,c,d,e){g.ND.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.u=[]},kFa=function(a){var b="_"+J3++;
return new I3(0,0x8000000000000,0,b,a)},mFa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Yc){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=lFa(l.textContent,n.textContent,p.textContent,f.textContent,h);return new H3(a,b,e,c,l,d,m)}switch(m.Yc){case 9:case 10:m.Eh=1;break;case 11:m.Eh=2;break;case 12:m.Eh=3;break;case 13:m.Eh=4;break;case 14:m.Eh=5}return new H3(a,b,e,c,l.textContent||"",d,m)},lFa=function(a,b,c,d,e){var f=g.Xj(),h=
f?g.Ee("DIV"):g.Ee("RUBY"),l=g.Ee("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.Ee("DIV"):g.Ee("RP");a.textContent=b;h.appendChild(a);b=f?g.Ee("DIV"):g.Ee("RT");b.textContent=c;h.appendChild(b);c=e.Yc;if(10===c||11===c||12===c||13===c||14===c)if(g.lg(b,"text-emphasis-style","filled circle"),g.lg(b,"text-emphasis-color","currentcolor"),g.lg(b,"webkit-text-emphasis","filled circle"),11===e.Yc||13===e.Yc)g.lg(b,"webkit-text-emphasis-position","under left"),g.lg(b,"text-emphasis-position","under left");c=!0;if(4===e.Yc||7===e.Yc||12===e.Yc||
14===e.Yc)g.lg(h,"ruby-position","over"),g.lg(h,"-webkit-ruby-position","before");else if(5===e.Yc||6===e.Yc||11===e.Yc||13===e.Yc)g.lg(h,"ruby-position","under"),g.lg(h,"-webkit-ruby-position","after"),c=!1;e=f?g.Ee("DIV"):g.Ee("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.lg(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.lg(f,"display","none"),f=f.nextElementSibling,g.lg(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.lg(h.lastElementChild,"display","none"),d?(g.lg(h,"padding-top","0.6em"),g.lg(f,"top","0")):(g.lg(h,"padding-bottom","0.6em"),g.lg(f,"bottom","0")));return h},K3=function(){g.B.apply(this,arguments)},L3=function(a){K3.call(this);
this.G=a;this.D={};this.P={};this.W={};this.F="_"+J3++;this.N={};this.B=this.u=null;this.K=!0},M3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return Number(c)},N3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"===c},O3=function(a,b){var c=M3(a,b);
return void 0!==c?c:null},Q3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return P3.test(c),c},nFa=function(a,b){var c={},d=b.getAttribute("ws");
g.Wa(c,d?a.W[d]:a.G);d=O3(b,"mh");null!=d&&(c.mn=d);d=O3(b,"ju");null!=d&&(c.textAlign=d);d=O3(b,"pd");null!=d&&(c.u=d);d=O3(b,"sd");null!=d&&(c.C=d);d=Q3(b,"wfc");null!=d&&(c.windowColor=d);d=M3(b,"wfo");void 0!==d&&(c.windowOpacity=d/255);return c},oFa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Wa(c,a.P[d]);d=O3(b,"ap");null!=d&&(c.Qg=d);d=M3(b,"cc");null!=d&&(c.Wj=d);d=M3(b,"ah");null!=d&&(c.eg=d);d=M3(b,"rc");null!=d&&(c.B=d);d=M3(b,"av");null!=d&&(c.Hh=d);return c},pFa=function(a,b,c,d){var e={};
g.Wa(e,oFa(a,b));g.Wa(e,nFa(a,b));d?g.Yb(e,a.G)?(d=a.F,e=a.G):d="_"+J3++:d=b.getAttribute("id")||"_"+J3++;a=M3(b,"t")+c;b=M3(b,"d")||0x8000000000000;if(2===e.u||3===e.u)c=e.B,e.B=e.Wj,e.Wj=c;return new I3(a,b,0,d,e)},R3=function(a){K3.call(this);
this.G=a;this.u=new Map;this.D=new Map;this.F=new Map;this.B=new Map},S3=function(a){a=g.$d(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},qFa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.D.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.F.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.B=a);b=b.ccColCount;void 0!==b&&(f.Wj=b);if(2===f.u||3===f.u)b=f.B,f.B=f.Wj,f.Wj=b;return new I3(c,d,0,e,f)},U3=function(){this.C=this.time=this.mode=this.B=0;
this.D=new T3(this);this.F=new T3(this);this.u=[];this.clear()},sFa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{dl:a,
Rj:b,result:0};a=rFa[a];b=rFa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Rj===d;if(d)return{dl:a,Rj:b,result:1}}else if(b&128&&1<=a&&31>=a)return{dl:a,Rj:b,result:2};return{dl:a,Rj:b,result:3}},uFa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.C&&a.reset(),a.D.u.clear(),a.F.u.clear()):(a.C=0,tFa(a.D,b,c,d))},vFa=function(a,b){a.u.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.q(a.u),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?uFa(a,d.wA,d.xA,b):1===d.type&&a.B&496&&tFa(a.F,d.wA,d.xA,b);a.u.length=0},V3=function(){this.type=0},W3=function(){this.state=this.Rj=this.dl=0},wFa=function(){this.timestamp=this.u=0},X3=function(a){this.F=a;
this.C=[];this.u=this.B=this.row=0;this.style=new V3;for(a=this.D=0;15>=a;a++){this.C[a]=[];for(var b=0;32>=b;b++)this.C[a][b]=new wFa}},Y3=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.F.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.C[m][p];
if(0!==r.u){0===c&&(c=m,d=p);n=String.fromCharCode(r.u);var t=r.timestamp;t<e&&(e=t);r.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===r.u||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.F(c,d,e,l,f)}else for(d=c=0,f=e=a.F.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.C[h][m],r=p.u,0!==r&&(0===c&&(c=h,d=m),n=String.fromCharCode(r),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===r)l&&b.F(c,d,e,f,l),e=f,l="",d=c=0},BFa=function(a,b){switch(a){case 0:return xFa[(b&127)-32];
case 1:return yFa[b&15];case 2:return zFa[b&31];case 3:return AFa[b&31]}return 0},Z3=function(a){return a.C[a.row][a.B]},$3=function(a,b,c){2<=b&&1<a.B&&(--a.B,Z3(a).u=0);
var d=Z3(a);d.timestamp=a.F.time+0;d.u=BFa(b,c);32>a.B&&a.B++},CFa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.C[b+e][f],l=a.C[c+e][f];
h.u=l.u;h.timestamp=l.timestamp}},a4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.C[b+d][e].reset()},b4=function(a){a.row=0<a.u?a.u:1;
a.B=1;a4(a,0,15)},c4=function(a){this.C=a;
this.F=0;this.style=new V3;this.G=new X3(this.C);this.K=new X3(this.C);this.text=new X3(this.C);this.B=this.G;this.D=this.K;this.u=this.B},d4=function(a,b,c){var d=a.B,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.u||(Y3(d,c),b4(a.B),b4(a.D),d.row=15,d.u=b,e=!0)}a.style.set(3);a.u=d;a.u.style=a.style;a.C.mode=1<<d.D;e?d.B=1:d.u!==b&&(d.u>b?(Y3(d,c),a4(d,d.row-d.u,b)):d.row<b&&(b=d.u),d.u=b)},DFa=function(a){a.style.set(1);
a.u=a.D;a.u.u=0;a.u.style=a.style;a.C.mode=1<<a.u.D},EFa=function(a){a.style.set(4);
a.u=a.text;a.u.style=a.style;a.C.mode=1<<a.u.D},T3=function(a){this.B=a;
this.F=0;this.C=new c4(this.B);this.G=new c4(this.B);this.u=new W3;this.D=this.C},tFa=function(a,b,c,d){a.u.update();
b=sFa(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.dl;c=b.Rj;if(32<=e||!e)a.B.mode&a.B.B&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.D.u,b&96&&$3(a,0,b),c&96&&$3(a,0,c),0!==b&&0!==c&&3===a.style.type&&Y3(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.dl=e,b.Rj=c,b.state=2,b=e&8?a.G:a.C,a.D=b,a.B.mode=1<<(a.F<<2)+(b.F<<1)+(4===b.style.type?1:0),(a.B.mode|1<<(a.F<<2)+(b.F<<1)+(4!==b.style.type?1:0))&a.B.B))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.u;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.u&&(d=c.u,d===c.row))break;var f=1+c.row-c.u,h=1+d-c.u;CFa(c,h,f,c.u);b=f;e=c.u;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));a4(c,b,e)}}c.row=d;c.B=a+1}else switch(e&7){case 1:switch(c&112){case 32:$3(b.u,0,32);break a;case 48:57===c?(d=b.u,Z3(d).u=0,32>d.B&&d.B++):$3(b.u,1,c&15)}break;case 2:c&32&&$3(b.u,2,c&31);break;case 3:c&32&&$3(b.u,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:DFa(b);
break;case 33:d=b.u;1<d.B&&(--d.B,Z3(d).u=0);break;case 36:d=b.u;b=Z3(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.C[a][c]===b){for(;32>=c;c++)d.C[a][c].reset();break}break;case 37:d4(b,2,d);break;case 38:d4(b,3,d);break;case 39:d4(b,4,d);break;case 40:$3(b.u,0,32);break;case 41:b.style.set(2);b.u=b.B;b.u.u=0;b.u.style=b.style;b.C.mode=1<<b.u.D;break;case 42:d=b.text;d.u=15;d.style.set(4);b4(d);EFa(b);break;case 43:EFa(b);break;case 44:a=b.B;switch(b.style.get()){case 1:case 2:case 3:Y3(a,d)}a4(a,
0,15);break;case 45:b:{a=b.u;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.B=1;break b}case 3:}2>a.u&&(a.u=2,a.row<a.u&&(a.row=a.u));b=a.row-a.u+1;Y3(a,d);CFa(a,b,b+1,a.u-1);a4(a,a.row,1)}break;case 46:a4(b.D,0,15);break;case 47:Y3(b.B,d),b.D.updateTime(b.C.time+0),d=b.D,b.D=b.B,b.B=d,DFa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.u,32<(d.B+=c&3)&&(d.B=32)}}},FFa=function(){},e4=function(a,b,c){this.N=a;
this.K=c;this.version=this.G=this.D=this.u=0;this.B=new DataView(this.N);this.C=[]},f4=function(a){var b=a.u;
a.u+=1;return a.B.getUint8(b)},g4=function(a){var b=a.u;
a.u+=4;return a.B.getUint32(b)},h4=function(a,b){K3.call(this);
this.B=a;this.D=b;this.track="CC3"===this.D.languageName?4:0;this.u=new U3;this.u.B=1<<this.track},i4=function(a){if("string"===typeof a)return!1;
a=new e4(a,8,0);return GFa(a)},GFa=function(a){if(!(a.u<a.B.byteLength)||1380139777!==g4(a))return!1;
a.version=f4(a);if(1<a.version)return!1;f4(a);f4(a);f4(a);return!0},j4=function(){K3.call(this)},HFa=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.ih=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new H3(b,c,d,e.id,p.nodeValue,f||0<n,g.Wb(l)?void 0:l),m.push(p),e.u.push(p);else{var r={};g.Wa(r,l);HFa(a,b,c,d,e,!0,p,r,m)}}},k4=function(a){var b=a.split(":");
a=0;b=g.q(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},IFa=function(a,b,c,d){d=Object.assign({mn:0},d);
return new I3(a,b,c,"_"+J3++,d)},l4=function(a){g.B.call(this);
this.B=a;this.u=null},KFa=function(a){var b={};
if(a=w3(a))b.lang=a,JFa.test(a)&&(b.u=1);return b},o4=function(a){g.AS.call(this,a);
this.J=a;this.C=this.J.T();this.videoData=this.J.getVideoData();this.Pa=g.KG(this.J);this.D={sc:{}};this.F={sc:{}};this.W=[];this.P={};this.ka={};this.ba=!1;this.Ea=g.zxa(this.videoData,this.J);this.Qa=!!this.videoData.captionTracks.length;this.bb=!!this.videoData.yo;this.za="3"===this.C.controlsType;this.B=this.K=this.N=this.ia=this.Aa=null;this.ra=new l4(this.C);this.u=null;this.ea=new g.os(this);var b=null,c=g.go("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Qn(c));this.storage=b;
b=a.app.F;c=!(!b||!b.yq());this.Ja=!(!b||!b.mm());this.G=this.za&&c&&!this.Ea;this.Y=!this.G&&this.za&&this.Ja&&this.Ea;g.C(this,this.ra);this.G?this.da=this.X=null:(this.X=new g.nn(this.sG,void 0,this),g.C(this,this.X),this.da=new g.E(this.nQ,2E3,this),g.C(this,this.da));g.C(this,this.ea);this.G||this.ea.R(a,"resize",this.kz);this.ea.R(a,"onPlaybackAudioChange",this.GM);this.ea.R(a,g.QD("captions"),this.RK,this);this.ea.R(a,g.RD("captions"),this.SK,this);m4(this,n4(this,"display-settings")||{})},
LFa=function(a){if(1===a.C.Ti||1===a.videoData.Ti||"alwayson"===g.VF(a.videoData,"yt:cc"))return!0;
if(2===a.C.Ti){var b=n4(a,"module-enabled");if(null!=b)return!!b}if(a.videoData.captionTracks.length)var c=a.player.getAudioTrack().C;return"ON"===c||"on"===g.VF(a.videoData,"yt:cc")},p4=function(a,b){if(a.u&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.B||"FORCED_ON"===c.C},MFa=function(a){var b=!1,c=g.gs(g.es.getInstance(),65);
g.IC(a.C)&&null!=c&&(b=!c);return b},NFa=function(a){return a.za?a.G||a.Y:MFa(a)||p4(a)?!0:LFa(a)},r4=function(a,b){if(a.B){if(a.K&&a.K.F)return a.K.F;
var c=b;c||(c=a.bb?!1:a.Qa?!1:!0);c=a.B.Cl(c);for(var d=[a.videoData.captionsLanguagePreference,a.C.captionsLanguagePreference,g.VF(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(w3(c[f])===d[e])return c[f];return a.K&&a.K.D?a.K.D:(d=c.find(function(h){return h.isDefault}))?d:c[0]||q4(a)}return null},q4=function(a){return a.K&&a.K.B},s4=function(a){var b=q4(a);
return!!b&&a.u===b},OFa=function(a,b){for(var c=a.J.app.F.Ma().textTracks,d=a.u.toString(),e=0;e<c.length;e++){var f=c[e];
f.id===d&&(b?"showing"!==f.mode&&(f.mode="showing"):"showing"===f.mode&&(f.mode="disabled"))}},u4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.ba=c,a.ba&&t4(a,"module-enabled",!!b));a.u=b;p4(a)&&(a.u=q4(a));a.load()},PFa=function(a,b){var c=a.Pa.getVideoContentRect(!0).height;
if(!c)return null;var d=a.u?a.u.languageCode:null;!b.params.u&&d&&JFa.test(d)&&(b.params.u=1);d=a.Pa.getPlayerSize();switch(null!=b.params.mn?b.params.mn:1<b.u.length?1:0){case 1:return new F3(b,a.D,a.F,c,d.width,d.height,a.C.experiments);case 2:return new G3(b,a.D,a.F,c,d.width,d.height,a.C.experiments);default:return new E3(b,a.D,a.F,c,d.width,d.height,a.C.experiments)}},m4=function(a,b,c){c=void 0===c?!1:c;
var d=v4.sc;a.D={};g.Wa(a.D,v4);a.D.sc={};g.Wa(a.D.sc,d);a.F={sc:{}};var e=b.backgroundOverride?a.F:a.D,f=b.background||d.background;P3.test(f);e.sc.background=f;e=b.colorOverride?a.F:a.D;f=b.color||d.color;P3.test(f);e.sc.color=f;e=b.windowColorOverride?a.F:a.D;f=b.windowColor||v4.windowColor;P3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.F:a.D;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.sc.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.F:a.D;f=b.fontSizeIncrement;null==
f&&(f=d.fontSizeIncrement);e.sc.fontSizeIncrement=f;f=b.fontStyleOverride?a.F:a.D;e=b.fontStyle;null==e&&(e=d.bold&&d.ih?3:d.bold?1:d.ih?2:0);f=f.sc;switch(e){case 1:f.bold=!0;delete f.ih;break;case 2:delete f.bold;f.ih=!0;break;case 3:f.bold=!0;f.ih=!0;break;default:delete f.bold,delete f.ih}e=b.textOpacityOverride?a.F:a.D;f=b.textOpacity;null==f&&(f=d.textOpacity);e.sc.textOpacity=f;e=b.windowOpacityOverride?a.F:a.D;f=b.windowOpacity;null==f&&(f=v4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.F:a.D;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.sc.charEdgeStyle=f;e=b.fontFamilyOverride?a.F:a.D;f=b.fontFamily;null==f&&(f=d.fontFamily);e.sc.fontFamily=f;a.loaded&&a.kz();c&&t4(a,"display-settings",b)},RFa=function(a,b){if(b&&!a.N){var c=kFa({u:0,
lang:"en"});a.N=[c,new H3(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.hN(a.player,a.N)}else!b&&a.N&&(QFa(a,a.N),a.N=null)},QFa=function(a,b){g.iN(a.player.app,b,void 0);
g.Fb(b,function(c){g.rb(this.W,c)},a);
a.X.Gb()},n4=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},t4=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}};
g.OS.prototype.Bo=g.ca(11,function(){for(var a=g.oe(document,"track",void 0,this.u),b=0;b<a.length;b++)g.Ie(a[b])});
g.PS.prototype.Bo=g.ca(10,function(){this.u.Bo()});
g.OS.prototype.yq=g.ca(9,function(){return!!this.u.textTracks});
g.PS.prototype.yq=g.ca(8,function(){return this.u.yq()});
g.OS.prototype.qo=g.ca(7,function(a){for(var b=0;b<a.length;b++)this.u.appendChild(a[b])});
g.PS.prototype.qo=g.ca(6,function(a){this.u.qo(a)});
g.IS.prototype.mm=g.ca(5,function(){});
g.OS.prototype.mm=g.ca(4,function(){return!(!this.u.textTracks||!this.u.textTracks.addEventListener)});
g.PS.prototype.mm=g.ca(3,function(){return this.u.mm()});
g.yw.prototype.gs=g.ca(1,function(){return 0});
g.Gz.prototype.gs=g.ca(0,function(a){return(a=this.ai(a))?a.B:0});
var JFa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;TEa.prototype.Cl=function(a){return a?this.u.concat(this.B):this.u};
g.u(y3,g.B);g.k=y3.prototype;g.k.Cl=function(a){return this.B.Cl(a)};
g.k.Ss=function(){};
g.k.Ts=function(){};
g.k.Ij=function(){};
g.k.Wm=function(){return""};
g.k.eF=function(){return!1};
g.k.aa=function(){this.Ij();g.B.prototype.aa.call(this)};
g.u(z3,y3);z3.prototype.Ss=function(a,b,c){var d=this;this.la();b=this.Wm(a,b);this.Ij();this.u=g.mq(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})};
z3.prototype.Ts=function(a){if(this.audioTrack)for(var b=g.q(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())x3(this.B,c.value);a()};
z3.prototype.Wm=function(a,b){var c=a.rd(),d={fmt:b};if("srv3"===b||"3"===b||"json3"===b)g.Xj()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.translationLanguage&&(d.tlang=w3(a));return g.Xp(c,d)};
z3.prototype.Ij=function(){this.u&&this.u.abort()};
A3.prototype.contains=function(a){a=g.Ab(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
A3.prototype.length=function(){return this.segments.length/2};
g.u(B3,g.B);g.k=B3.prototype;g.k.aa=function(){g.B.prototype.aa.call(this);this.B&&this.B.cancel()};
g.k.iD=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.oc();var b=this.u;this.u=g.gb(this.W.ej(a).u);b!==this.u&&this.N&&this.N()};
g.k.reset=function(){this.D=new A3;this.B&&(this.B.cancel(),this.B=null)};
g.k.EC=function(){this.la();var a;if(a=null!=this.u)a=this.u,a=a.u.wj(a);!a||this.B||this.u&&30<this.u.startTime-this.player.getCurrentTime()||(a=this.u.ek(),a.u[0].duration?(this.D.contains(a.u[0].B)||WEa(this,a),this.u=g.gb(a.u)):!g.Q(this.P.experiments,"force_caption_seek_for_live_killswitch")&&this.u&&this.u.G&&this.u.G+this.player.oc()<this.player.getCurrentTime()&&this.seekTo(this.player.getCurrentTime()));this.K.start()};
g.u(C3,y3);g.k=C3.prototype;g.k.Ss=function(a,b,c){var d=this;this.Ij();b=YEa(this,a.getId());b||(b=a.languageCode,b=this.ma.isManifestless?ZEa(this,b,"386"):ZEa(this,b));if(b){var e=1E3*(b.index.gs(b.index.Zg())-b.index.Fe(b.index.Zg()));this.u=new B3(new g.vv,this.J,b,function(f,h){c(f,a,h,e)},this.F||g.kv(b.info),function(){d.u&&d.u.reset();
d.C=!0})}};
g.k.eF=function(){var a=this.C;this.C=!1;return a};
g.k.Ts=function(a){var b=this.F?[new g.RE({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.RE({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.ma.isManifestless?XEa(this,"386"):XEa(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())x3(this.B,c.value);a()};
g.k.Ij=function(){this.u&&(this.u.dispose(),this.u=null)};
g.k.Wm=function(){return""};
g.u(D3,y3);D3.prototype.Ss=function(a,b,c){var d=this;this.la();b=this.Wm(a,b);this.Ij();this.u=g.mq(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})};
D3.prototype.Ts=function(a){var b=this,c=this.C,d={type:"list",tlangs:1,v:this.videoId,vssids:1};this.bC&&(d.asrs=1);c=g.Xp(c,d);this.Ij();this.u=g.mq(c,{format:"RAW",onSuccess:function(e){b.u=null;if((e=e.responseXML)&&e.firstChild){for(var f=e.getElementsByTagName("track"),h=0;h<f.length;h++){var l=f[h],m=l.getAttribute("lang_code"),n=l.getAttribute("lang_translated"),p=l.getAttribute("name"),r=l.getAttribute("kind"),t=l.getAttribute("id"),w="true"===l.getAttribute("lang_default"),x="true"===l.getAttribute("cantran");
l=l.getAttribute("vss_id");x3(b.B,new g.RE({languageCode:m,languageName:n,name:p,kind:r,id:t,is_servable:!0,is_translateable:x,vss_id:l,is_default:w}))}e=e.getElementsByTagName("target");f=e.length;for(h=0;h<f;h++)m={languageCode:e[h].getAttribute("lang_code"),languageName:e[h].getAttribute("lang_translated"),languageOriginal:e[h].getAttribute("lang_original"),id:e[h].getAttribute("id"),isDefault:"true"===e[h].getAttribute("lang_default")},b.F[m.languageCode]=m.languageName,b.D.push(m)}a()},
withCredentials:!0})};
D3.prototype.Wm=function(a,b){var c=this.C,d={v:this.videoId,type:"track",lang:a.languageCode,name:a.getName(),kind:a.kind,fmt:b};a.translationLanguage&&(d.tlang=w3(a));return c=g.Xp(c,d)};
D3.prototype.Ij=function(){this.u&&this.u.abort()};
var P3=/^#(?:[0-9a-f]{3}){1,2}$/i;var aFa=["left","right","center","justify"];g.u(E3,g.V);g.k=E3.prototype;g.k.QK=function(a,b){var c=g.zg(this.element,this.element.parentElement);this.za=a-c.x;this.Ea=b-c.y;g.G(this.element,"ytp-dragging")};
g.k.PK=function(a,b){var c=g.Bg(this.element),d=a-this.za-.02*this.playerWidth,e=b-this.Ea-.02*this.playerHeight,f=(d+c.width/2)/this.maxWidth*3;f=Math.floor(g.$d(f,0,2));var h=(e+c.height/2)/this.Ja*3;h=Math.floor(g.$d(h,0,2));var l=f+3*h;d=(d+f/2*c.width)/this.maxWidth;d=100*g.$d(d,0,1);c=(e+h/2*c.height)/this.Ja;c=100*g.$d(c,0,1);this.B.params.Qg=l;this.B.params.Hh=c;this.B.params.eg=d;this.u.Qg=l;this.u.Hh=c;this.u.eg=d;this.JF()};
g.k.OK=function(){g.yn(this.element,"ytp-dragging")};
g.k.JF=function(){this.Qn(this.F)};
g.k.Qn=function(a){var b=Math.min(this.uB(),this.maxWidth),c=this.tB(),d="";3===this.B.params.u&&(d="rotate(180deg)");g.lg(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.kv(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.u.eg+2;d=this.u.Qg;switch(d){case 0:case 3:case 6:b=this.u.sc.fontSizeIncrement;!g.Q(this.experiments,"web_player_ignore_left_percentage_for_large_font_killswitch")&&
b&&2<b&&2!==this.u.u&&3!==this.u.u&&(e=2);a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.D.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.u.Hh+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-
b+"%"}g.lg(this.element,a)};
g.k.kv=function(a){var b;for(b=0;b<a.length&&a[b]===this.F[b];b++);if(this.Y||this.F.length>b)b=0,this.Y=!1,this.F=[],this.G=this.ea=this.ba=null,g.Ge(this.D);for(;b<a.length;b++)eFa(this,a[b])};
g.k.uB=function(){return 0};
g.k.tB=function(){return 0};
g.k.toString=function(){return g.V.prototype.toString.call(this)};g.u(F3,E3);F3.prototype.kv=function(a){var b=this.B.u;E3.prototype.kv.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.u===e)var d=f;else{d={};g.Wa(d,c.u);g.Wa(d,SFa);var e=c.u;var f=d}eFa(this,c,d)}};
var SFa={wJ:!0};g.u(G3,E3);g.k=G3.prototype;g.k.JF=function(){g.qn(this.ka)};
g.k.PO=function(){g.yn(this.element,"ytp-rollup-mode");this.Qn(this.qb,!0)};
g.k.tB=function(){return this.C?this.W:this.P};
g.k.uB=function(){return this.C?this.P:this.W};
g.k.Qn=function(a,b){this.qb=a;if(this.B.params.B){for(var c=0,d=0;d<this.F.length&&c<a.length;d++)this.F[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.F.concat(a.slice(c)));this.Pa=this.W;this.P=this.W=0;E3.prototype.Qn.call(this,a);jFa(this,b)}E3.prototype.Qn.call(this,a)};g.u(H3,g.ND);H3.prototype.toString=function(){return g.ND.prototype.toString.call(this)};g.u(I3,g.ND);I3.prototype.toString=function(){return g.ND.prototype.toString.call(this)};
var J3=0;g.u(K3,g.B);K3.prototype.C=function(){return[]};
K3.prototype.reset=function(){};g.u(L3,K3);L3.prototype.reset=function(){this.N={};this.B=this.u=null;this.K=!0};
L3.prototype.C=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var h=this.D,l={},m=c.getAttribute("p");m&&g.Wa(l,this.D[m]);m=N3(c,"b");null!=m&&
(l.bold=m);m=N3(c,"i");null!=m&&(l.ih=m);m=N3(c,"u");null!=m&&(l.underline=m);m=O3(c,"et");null!=m&&(l.charEdgeStyle=m);m=O3(c,"of");null!=m&&(l.offset=m);m=Q3(c,"bc");null!=m&&(l.background=m);m=Q3(c,"ec");null!=m&&(l.Dv=m);m=Q3(c,"fc");null!=m&&(l.color=m);m=O3(c,"fs");null!=m&&0!==m&&(l.fontFamily=m);m=M3(c,"sz");void 0!==m&&(l.fontSizeIncrement=m/100-1);m=M3(c,"bo");void 0!==m&&(l.backgroundOpacity=m/255);m=M3(c,"fo");void 0!==m&&(l.textOpacity=m/255);m=O3(c,"rb");null!=m&&10!==m&&0!==m&&(l.Yc=
10<m?m-1:m);c=O3(c,"hg");null!=c&&(l.XB=c);h[d]=l;break;case "ws":d=c.getAttribute("id");this.W[d]=nFa(this,c);break;case "wp":d=c.getAttribute("id"),this.P[d]=oFa(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "w":this.u=pFa(this,d,e,!1);(d=this.N[this.u.id])&&d.end>this.u.start&&(d.end=this.u.start);this.N[this.u.id]=this.u;c.push(this.u);break;case "p":var n=e;h=[];l=d.getAttribute("w")||this.F;m=!!N3(d,
"a");n=(M3(d,"t")||0)+n;var p=M3(d,"d")||5E3;m||(!this.K&&this.B&&this.B.windowId===l&&this.B.end>n&&(this.B.end=n),this.B&&"\n"===this.B.text&&(this.B.text=""));var r=m?6:5,t=d.getAttribute("p");t=t?this.D[t]:null;var w=Array.from(d.childNodes);w.length&&(this.K=null!=d.getAttribute("d"));for(var x=0;x<w.length;x++){var y=w[x],D=void 0;0<x&&(m=!0);var F=void 0;1===y.nodeType&&(F=y);if(F&&"s"===F.tagName){if((y=(y=F.getAttribute("p"))?this.D[y]:null)&&y.Yc&&(1===y.Yc?(y=w.slice(x,x+4),4===y.length&&
(D=mFa(n,p,l,m,r,y,this.D),x+=3)):D=mFa(n,p,l,m,r,[F],this.D)),!D){var H=F;D=n;F=p;y=l;var M=m,J=r,Ka=H.textContent?H.textContent:"",va=H.getAttribute("p");va=va?this.D[va]:null;H=M3(H,"t")||0;D=new H3(D+H,F-H,J,y,Ka,M,va)}}else D=new H3(n,p,r,l,y.textContent||"",m,t);h.push(D);this.B=D}if(0<h.length)for(h[0].windowId===this.F&&(this.u=pFa(this,d,e,!0),c.push(this.u)),d=g.q(h),h=d.next();!h.done;h=d.next())h=h.value,h.windowId=this.u.id,this.u.u.push(h),c.push(h)}e=c}else e=[];return e};var TFa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.u(R3,K3);R3.prototype.reset=function(){this.B.clear()};
R3.prototype.C=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens)for(var d=0,e=g.q(c.pens),f=e.next();!f.done;f=e.next()){f=f.value;var h={},l=f.pParentId;l&&Object.assign(h,this.u.get(l));f.bAttr&&(h.bold=!0);f.iAttr&&(h.ih=!0);f.uAttr&&(h.underline=!0);l=f.ofOffset;null!=l&&(h.offset=l);void 0!==f.szPenSize&&(h.fontSizeIncrement=f.szPenSize/100-1);l=f.etEdgeType;null!=l&&(h.charEdgeStyle=l);void 0!==f.ecEdgeColor&&(h.Dv=S3(f.ecEdgeColor));l=f.fsFontStyle;null!=l&&0!==l&&(h.fontFamily=l);
void 0!==f.fcForeColor&&(h.color=S3(f.fcForeColor));void 0!==f.foForeAlpha&&(h.textOpacity=f.foForeAlpha/255);void 0!==f.bcBackColor&&(h.background=S3(f.bcBackColor));void 0!==f.boBackAlpha&&(h.backgroundOpacity=f.boBackAlpha/255);(l=f.rbRuby)&&10!==l&&(h.Yc=10<l?l-1:l,h.Eh=TFa.get(h.Yc));f.hgHorizGroup&&(h.XB=f.hgHorizGroup);this.u.set(d++,h)}if(c.wsWinStyles)for(d=0,e=g.q(c.wsWinStyles),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wsParentId)?Object.assign(h,this.F.get(l)):Object.assign(h,
this.G),void 0!==f.mhModeHint&&(h.mn=f.mhModeHint),void 0!==f.juJustifCode&&(h.textAlign=f.juJustifCode),void 0!==f.pdPrintDir&&(h.u=f.pdPrintDir),void 0!==f.sdScrollDir&&(h.C=f.sdScrollDir),void 0!==f.wfcWinFillColor&&(h.windowColor=S3(f.wfcWinFillColor)),void 0!==f.wfoWinFillAlpha&&(h.windowOpacity=f.wfoWinFillAlpha/255),this.F.set(d++,h);if(c.wpWinPositions)for(d=0,e=g.q(c.wpWinPositions),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wpParentId)&&Object.assign(h,this.D.get(l)),void 0!==f.ahHorPos&&
(h.eg=f.ahHorPos),void 0!==f.apPoint&&(h.Qg=f.apPoint),void 0!==f.avVerPos&&(h.Hh=f.avVerPos),void 0!==f.ccCols&&(h.Wj=f.ccCols),void 0!==f.rcRows&&(h.B=f.rcRows),this.D.set(d++,h);if(c.events)for(d=[],c=g.q(c.events),e=c.next();!e.done;e=c.next()){var m=e.value;e=(m.tStartMs||0)+b;f=m.dDurationMs||0;if(m.id)h=String(m.id),e=qFa(this,m,e,f,h),d.push(e),this.B.set(h,e);else{m.wWinId?h=m.wWinId.toString():(h="_"+J3++,l=qFa(this,m,e,f,h),d.push(l),this.B.set(h,l));0===f&&(f=5E3);l=this.B.get(h);var n=
!!m.aAppend,p=n?6:5,r=m.segs,t=null;m.pPenId&&(t=this.u.get(m.pPenId));for(m=0;m<r.length;m++){var w=r[m],x=w.utf8;if(x){var y=w.tOffsetMs||0,D=null;w.pPenId&&(D=this.u.get(w.pPenId));if(2===(null!=l.params.mn?l.params.mn:1<l.u.length?1:0)&&n&&"\n"===x)continue;if(w=D&&1===D.Yc)if(w=m,w+3>=r.length||!r[w+1].pPenId||!r[w+2].pPenId||!r[w+3].pPenId)w=!1;else{var F=r[w+1].pPenId;(F=this.u.get(F))&&F.Yc&&2===F.Yc?(F=r[w+2].pPenId,F=this.u.get(F),!F||!F.Yc||3>F.Yc?w=!1:(F=r[w+3].pPenId,w=(F=this.u.get(F))&&
F.Yc&&2===F.Yc?!0:!1)):w=!1}if(w){y=r[m+1].utf8;w=r[m+3].utf8;F=r[m+2].utf8;var H=this.u.get(r[m+2].pPenId);x=lFa(x,y,F,w,H);n=new H3(e,f,p,h,x,n,D);m+=3}else n=new H3(e+y,f-y,p,l.id,x,n,D||t);n&&(d.push(n),l.u.push(n))}n=!0}}}else d=[];return d};U3.prototype.clear=function(){this.C=this.time=this.mode=0;this.u=[];this.reset()};
U3.prototype.reset=function(){this.mode=0;this.D.reset(0);this.F.reset(1)};
var rFa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];V3.prototype.set=function(a){this.type=a};
V3.prototype.get=function(){return this.type};
W3.prototype.clear=function(){this.state=0};
W3.prototype.update=function(){this.state=2===this.state?1:0};
W3.prototype.isValid=function(){return 0!==this.state};
W3.prototype.matches=function(a,b){return this.isValid()&&a===this.dl&&b===this.Rj};
wFa.prototype.reset=function(){this.timestamp=this.u=0};
X3.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.C[b][c].timestamp=a};
X3.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.C[b][c];a=0===d.u?a+"_":a+String.fromCharCode(d.u)}a+="\n"}return a};
X3.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.C[b][c].reset();this.D=a;this.u=0;this.B=this.row=1};
var xFa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],yFa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],zFa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],AFa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];c4.prototype.reset=function(a,b){this.F=b;this.style.set(2);this.B=this.G;this.D=this.K;this.u=this.B;var c=(a<<2)+(b<<1);this.G.reset(c);this.K.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
T3.prototype.reset=function(a){this.F=a;this.u.clear();this.D=this.C;this.C.reset(a,0);this.G.reset(a,1)};FFa.prototype.F=function(){};g.u(e4,FFa);e4.prototype.F=function(a,b,c,d,e){if(c<d){var f="_"+J3++;c=c/1E3-this.K;d=d/1E3-this.K;a=new I3(c,d-c,5,f,{textAlign:0,Qg:0,eg:2.5*b,Hh:5.33*a});e=new H3(c,d-c,5,f,e);this.C.push(a);this.C.push(e)}};
g.u(h4,K3);h4.prototype.C=function(a){a=new e4(a,a.byteLength,this.B);if(GFa(a)){for(;a.u<a.B.byteLength;)for(0===a.version?a.D=g4(a)*(1E3/45):1===a.version&&(a.D=4294967296*g4(a)+g4(a)),a.G=f4(a);0<a.G;a.G--){var b=f4(a),c=f4(a),d=f4(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.u,b.u.push({time:a.D,type:this.track,wA:c,xA:d,order:b.u.length}))}vFa(this.u,a);return a.C}return[]};
h4.prototype.reset=function(){this.u.clear()};g.u(j4,K3);
j4.prototype.C=function(a,b){for(var c=[],d=a.split(UFa),e=1;e<d.length;e++){var f=d[e],h=b;if(""!==f&&!VFa.test(f)){var l=w4.exec(f);if(l&&4<=l.length){var m=k4(l[1]),n=k4(l[2])-m;m+=h;var p=(l=l[3])?l.split(" "):[];l={};var r=null,t="",w=null,x="";l.textAlign=2;p=g.q(p);for(var y=p.next();!y.done;y=p.next())if(y=y.value.split(":"),2===y.length){var D=y[1];switch(y[0]){case "line":y=D.split(",");y[0].endsWith("%")&&(r=y[0],l.Hh=Number.parseInt(r,10),2===y.length&&(t=y[1].trim()));break;case "position":y=
D.split(",");w=y[0];l.eg=Number.parseInt(w,10);2===y.length&&(x=y[1].trim());break;case "align":switch(D){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}r||(l.Hh=100,t||(t="end"));if(!w)switch(l.textAlign){case 0:l.eg=0;break;case 1:l.eg=100;break;default:l.eg=50}r=0;switch(t){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(x){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.Qg=0>r||8<r?7:r;f=f.substring(w4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");x=l;l=f;f={};if(0>l.indexOf("<")&&0>l.indexOf("&"))h=IFa(m,n,5,x),n=new H3(m,n,5,h.id,l,!1,g.Wb(f)?void 0:f),c.push(h),c.push(n),h.u.push(n);else for(t=l.split(WFa),1===t.length?(l=5,x=IFa(m,n,l,x)):(r=l=6,x=Object.assign({Wj:32},x),x=new I3(m,n,r,"_"+J3++,x)),c.push(x),r=m,w=0;w<t.length;w++)p=t[w],0===w%2?(y=g.k1("<html>"+p+"</html>"),y.getElementsByTagName("parsererror").length?
(D=y.createElement("span"),D.appendChild(y.createTextNode(p))):D=y.firstChild,HFa(this,r,n-(r-m),l,x,0<w,D,f,c)):r=k4(p)+h}w4.lastIndex=0}}return c};
var VFa=/^NOTE/,UFa=/(?:\r\n|\r|\n){2,}/,w4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),WFa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.u(l4,g.B);l4.prototype.clear=function(){this.u&&this.u.dispose();this.u=null};
l4.prototype.reset=function(){this.u&&this.u.reset()};
l4.prototype.aa=function(){g.B.prototype.aa.call(this);this.clear()};var v4={windowColor:"#080808",windowOpacity:0,textAlign:2,Qg:7,eg:50,Hh:100,sc:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.u(o4,g.AS);g.k=o4.prototype;g.k.aa=function(){if(this.G||this.Y){var a=this.J.app.F;a&&!a.la()&&a.Bo()}else RFa(this,!1);g.AS.prototype.aa.call(this)};
g.k.load=function(){var a=this;g.AS.prototype.load.call(this);var b=!g.Q(this.C.experiments,"web_player_captions_track_list_changed_killswitch");this.K=this.player.getAudioTrack();if(this.B)this.u&&(this.ra.clear(),this.G?OFa(this,!0):3!==this.player.getPresentingPlayerType()&&this.B.Ss(this.u,"json3",function(d,e,f,h){if(d){a.B.eF()&&(a.W=[],g.pX(a.J,"captions"),a.X.Gb(),a.ra.reset());var l=a.ra;f=f||0;h=h||0;if(l.B.ca("html5_disable_rawcc_killswitch")){if("string"!==typeof d){var m=new DataView(d);
8<=m.byteLength&&1718909296===m.getUint32(4)&&(m=g.Vt(m,0,1835295092),d=d.slice(m.dataOffset,m.dataOffset+m.size),i4(d)||(d=g.Ve(new Uint8Array(d))))}}else"string"===typeof d||i4(d)||(m=new DataView(d),d=8>=m.byteLength||1718909296!==m.getUint32(4)?"":(m=g.Vt(m,0,1835295092))&&m.size?g.Ve(new Uint8Array(d.slice(m.dataOffset,m.dataOffset+m.size))):"");if(d)try{if("string"!==typeof d){var n=d,p=f,r=h;if(!i4(n))throw Error("Invalid binary caption track data");l.u||(l.u=new h4(r,e));var t=l.u.C(n,p)}else{if("WEBVTT"===
d.substring(0,6))e=d,r=f,l.u||(l.u=new j4),p=l.u.C(e,r),.01>Math.random()&&g.Fr(Error("Deprecated subtitles format in web player: WebVTT")),n=p;else b:{p=d;if("{"===p[0])try{l.u||(l.u=new R3(KFa(e)));n=l.u.C(p,f);break b}catch(H){g.Er(H);n=[];break b}r=g.k1(p);if(!r||!r.firstChild){var w=Error("Invalid caption track data");w.params=p;throw w;}if("timedtext"===r.firstChild.tagName){if(3===Number(r.firstChild.getAttribute("format"))){l.u||(l.u=new L3(KFa(e),l.B));n=l.u.C(r,f);break b}var x=Error("Unsupported subtitles format in web player (Format2)");
x.params=p;throw x;}if("transcript"===r.firstChild.tagName){var y=Error("Unsupported subtitles format in web player (Format1)");y.params=p;throw y;}var D=Error("Invalid caption track data");D.params=p;throw D;}t=n}var F=t}catch(H){g.Er(H),l.clear(),F=[]}else F=[];g.hN(a.player,F);!a.ba||a.Y||s4(a)||g.rC(a.C)||g.sC(a.C)||(a.da.Xf(),F=kFa({Qg:0,eg:5,Hh:5,B:2,textAlign:0,u:0,lang:"en"}),a.ia=[F],l=["Click "," for settings"],a.Aa||(t=new g.uN(g.toa()),g.C(a,t),a.Aa=t.element),t=F.end-F.start,(e=g.SE(a.u))&&
a.ia.push(new H3(F.start,t,0,F.id,e)),a.ia.push(new H3(F.start,t,0,F.id,l[0]),new H3(F.start,t,0,F.id,a.Aa,!0),new H3(F.start,t,0,F.id,l[1],!0)),g.hN(a.player,a.ia),a.da.Gb());!a.ba||a.Y||s4(a)||(t4(a,"module-enabled",!0),a.K&&(a.K.F=a.u),(F=g.Z(a.player.app))&&g.XT(F.G));a.ba=!1}}),!b||this.G||this.Y||s4(this)||this.player.xa("captionschanged",v3(this.u))),b||(this.u&&!s4(this)?this.player.xa("captionschanged",v3(this.u)):this.player.xa("onCaptionsTrackListChanged"));
else{var c;this.Ea?c=new C3(this.videoData.ma,this.player):this.Qa?c=new z3(this.C,this.videoData,this.player.getAudioTrack()):c=new D3(this.videoData.yo,this.videoData.videoId,this.videoData.captionsLanguagePreference||this.C.captionsLanguagePreference||g.VF(this.videoData,"yt:cc_default_lang")||this.C.ue,this.videoData.zv,this.C);this.B=c;g.C(this,this.B);c.Ts(function(){var d;MFa(a)||a.ba||LFa(a)?d=r4(a,a.ba):p4(a)&&(d=q4(a));if(a.G||a.Y){for(var e=a.B.Cl(!0),f=[],h=0;h<e.length;h++){var l=e[h],
m=g.De("TRACK");m.setAttribute("kind","subtitles");m.setAttribute("label",g.SE(l));m.setAttribute("srclang",w3(l));m.setAttribute("id",l.toString());a.Y||m.setAttribute("src",a.B.Wm(l,"vtt"));l===d&&m.setAttribute("default","1");f.push(m)}d=a.J.app.F;d.qo(f);f=d.Ma();a.Ja&&a.ea.R(f.textTracks,"change",a.qP)}else!a.u&&d&&u4(a,d),a.player.xa("onCaptionsTrackListChanged"),a.player.xa("onApiChange")})}};
g.k.unload=function(){this.G&&this.u?OFa(this,!1):(this.da&&this.da.Xf(),g.pX(this.player,"captions"),this.W=[],this.B&&this.B.Ij(),this.ra.clear(),this.N&&g.hN(this.player,this.N),this.kz());g.AS.prototype.unload.call(this);var a=g.Z(this.player.app);a&&g.XT(a.G);this.player.xa("captionschanged",{})};
g.k.create=function(){NFa(this)&&this.load()};
g.k.qP=function(){for(var a=this.J.app.F.Ma().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;for(var d=this.B.Cl(!0),e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.u:null)!==b&&u4(this,b,!0)};
g.k.cR=function(){!this.u&&this.G||this.unload()};
g.k.RK=function(a){this.W.push(a);this.X.Gb()};
g.k.SK=function(a){g.rb(this.W,a);this.B instanceof C3&&this.B.F&&g.iN(this.player.app,[a],void 0);this.X.Gb()};
g.k.gQ=function(a){if(a instanceof I3){var b=this.P[a.id];b&&b.B!==a&&(b.dispose(),delete this.P[a.id],b=null);b||(b=PFa(this,a))&&(this.P[a.id]=b)}else b=a.windowId,this.ka[b]||(this.ka[b]=[]),this.ka[b].push(a)};
g.k.nQ=function(){QFa(this,this.ia);this.ia=null};
g.k.sG=function(){var a=this;this.X.stop();g.Xb(this.ka);this.W.sort(g.PD);var b=this.W;if(this.N){var c=g.Je(b,function(d){return-1===this.N.indexOf(d)},this);
c.length&&(b=c)}g.Fb(b,this.gQ,this);g.Ib(this.P,function(d,e){a.ka[e]?(d.element.parentNode||(d instanceof G3||d instanceof F3||g.Mb(a.P,function(f,h){h!==e&&f.B.params.Qg===d.B.params.Qg&&f.B.params.eg===d.B.params.eg&&f.B.params.Hh===d.B.params.Hh&&(f.dispose(),delete a.P[h]);return h===e},a),g.vP(a.player,d.element,4)),d.Qn(a.ka[e])):(d.dispose(),delete a.P[e])},this)};
g.k.rQ=function(){m4(this,{},!0);g.Q(this.C.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.xa("captionssettingschanged")};
g.k.QI=function(){var a=v4.sc;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.ih?3:a.bold?1:a.ih?2:0,textOpacity:a.textOpacity,windowColor:v4.windowColor,windowOpacity:v4.windowOpacity};var b=n4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.zG=function(a,b){var c={};g.Wa(c,n4(this,"display-settings"));g.Wa(c,a);m4(this,c,b);this.player.xa("captionssettingschanged")};
g.k.kz=function(){!this.G&&this.loaded&&(g.Ib(this.P,function(a,b){a.dispose();delete this.P[b]},this),this.sG())};
g.k.je=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.$d(b,-2,4);this.zG({fontSizeIncrement:c});return c;case "reload":b&&!this.G&&u4(this,this.u,!0);break;case "stickyLoading":void 0!==b&&this.C.C&&t4(this,"module-enabled",!!b);break;case "track":if(!this.B)return{};if(b){if(this.G)break;if(!g.Sa(b))break;if(g.Wb(b)){u4(this,null,!0);break}for(var d=this.B.Cl(!0),e=0;e<d.length;e++){var f=d[e];f.languageCode!==b.languageCode||c&&f.languageName!==b.languageName||(c=b.translationLanguage?
SEa(f,b.translationLanguage):f)}!c||c===this.u&&this.loaded||u4(this,c,!0)}else return this.loaded&&this.u&&!s4(this)?v3(this.u):{};return"";case "tracklist":return this.B?g.Pc(this.B.Cl(!(!b||!b.includeAsr)),function(h){return v3(h)}):[];
case "translationLanguages":return this.B?this.B.D.map(function(h){return Object.assign({},h)}):[];
case "sampleSubtitles":this.G||void 0===b||RFa(this,!!b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.C.C&&a.push("stickyLoading");return a};
g.k.RJ=function(){var a=this.u;return a?{cc:a.vssId}:{}};
g.k.TQ=function(){this.loaded&&this.u&&!s4(this)?(t4(this,"module-enabled",!1),this.unload(),p4(this,!0)&&u4(this,q4(this),!1)):u4(this,s4(this)||!this.u?r4(this,!0):this.u,!0)};
g.k.GM=function(){var a=s4(this);p4(this,a)?u4(this,this.player.getAudioTrack().B,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),NFa(this)&&(a?u4(this,r4(this),!1):this.load()))};g.DX.captions=o4;})(_yt_player);
